### ISSUE TITLE
RSS Not Scrolling after upgrade from 1.6.4 to 1.7.0

### ISSUE THREAD

**Issue by andyrogers2012** [xibosignage/xibo#100]
I have just recently started to test 1.7.0 before a planned live upgrade and am having an issue with RSS feeds not scrolling anymore with the new Client.

This has been upgraded from 1.6.4 and was working fine before hand, and shows as working in the Preview on the CMS.

**Comment by andyrogers2012** [comment]
Found error in Logs:-
<errormsg>include_once(): Failed opening 'modules/Ticker.module.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear')</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>/var/www/xibo_test/lib/pages/module.class.php</scriptname>
<scriptlinenum>274</scriptlinenum>

**Comment by andyrogers2012** [comment]
<errormsg>include_once(modules/Ticker.module.php): failed to open stream: No such file or directory</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>/var/www/xibo_test/lib/pages/module.class.php</scriptname>
<scriptlinenum>274</scriptlinenum>

**Comment by dasgarner** [comment]
Please can you try going to the Modules Page in the CMS and selecting the "Verify All" button in the top right.

The way scrolling works is the same, but the way we deliver that information to the player has changed (we deliver it in several separate files instead of one big one). My guess would be that those files have not been installed correctly as they should have been during the upgrade.

**Comment by andyrogers2012** [comment]
Hi, thanks for the reply.  I have done that and all came back ok.
Tried again and still getting same error messages in the logs.
Suggestions?

**Comment by andyrogers2012** [comment]
Also this message has appeared in the logs now:-	
<errormsg>Undefined variable: link</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>/var/www/xibo_test/modules/ticker.module.php</scriptname>
<scriptlinenum>952</scriptlinenum>

**Comment by dasgarner** [comment]
I think you might be using some of the new functionality in 1.7.0 - namely the support for media RSS? I am supposing that in your template you have a substitution like [tag|image] ?

If so, then that notice in the logs is nothing to worry about (although I will just patch it).

I still think the problem is on the client end, are you sure your client has downloaded all of its required files (i.e. it has a tick on the display page against its status)?

**Comment by andyrogers2012** [comment]
Yes am, using media RSS.

Been back to re visit issue, and to my surprise all is working ok as expected and nothing has changed.
