### ISSUE TITLE
1.8.0-rc2 Daypart Schedule Finish

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1039]
When creating a schedule with a named daypart, there's no Finish box available on the form, so you can't control the date on which the schedule should finish.

![image](https://cloud.githubusercontent.com/assets/10450518/22824329/654da5f0-ef7f-11e6-8dac-28592787d200.png)

This may already be logged somewhere. I remember discussing it, but can't find reference to it.

OP: https://community.xibo.org.uk/t/scheduling-using-dayparts/8725

**Comment by dasgarner** [comment]
It is correct, as per the spec, to only display a start time for the event. 

The end time is governed by the day part you have selected. It is not possible for a day part event to span more than one day. 

Repeating schedules can be used to achieve multi-day events.

**Comment by dasgarner** [comment]
Make adjustments to the form so that it is obvious that events with a Daypart only apply to 1 day, unless a recurring schedule is set.

Having an "end date" in the traditional sense makes things very complex. All other events are "single time period", but if we have an end-date on day part events then each event will actually spawn multiple events (because there will be a unique event for each day between the start/end times).
