### ISSUE TITLE
HTTPS RSS feed doesn't display (SSL3_GET_SERVER_CERTIFICATE:certificate verify failed)

### ISSUE THREAD

**Issue by RobKeeling** [xibosignage/xibo#111]
We have a Layout that contains student notices. After upgrading our live system this layout fails to display.

I have re-created the Layout from scratch, however I can not get a local RSS feed to display, I have  managed to get the BBC news RSS feed to display in it's place.

Are there any debugging steps I can follow to determine what is failing.

There does not appear to be a https request to the webserver according to the IIS logs and no XML files are stored in the "xibo library" folder on the screen,

**Comment by dasgarner** [comment]
Please can you run through the steps on the report fault page and then put the `troubleshoot.txt` file somewhere for us to look at?

The underlying library hasn't changed between those versions, but we do have some extra settings in place that might be effecting it/

In any case, the request will be logged in the log and present in the above file.

**Comment by RobKeeling** [comment]
I have run the Troubleshooting steps and the troubleshoot.txt file contains the following.

"2015-01-31 14:01:49","","","Loading SimplePie to handle RSS parsing.https://intranet.queenelizabeths.derbyshire.sch.uk/public/rss/index.php?filter=studentscreen"
"2015-01-31 14:01:49","","","Feed Error: cURL error 60: SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed"

Which sounds like the problem, the question is how to fix? Everything used to work, and the Wildcard SSL certificate is valid.

**Comment by RobKeeling** [comment]
After some research I found this https://github.com/simplepie/simplepie/issues/236

which suggested 

"For anyone looking to solve this problem using xpopov's solution, it can be implemented by editing File.php and adding curl_setopt($fp, CURLOPT_SSL_VERIFYPEER, false); around line 109."

Doing so has now started to read the RSS feed again. 

Is this worth adding as a bug fix?

Many thanks for the help Dan.

**Comment by dasgarner** [comment]
Hmm, well I am pleased you have solved your issue and as it sounds like you are using an internal feed its probably OK as a fix (if you use any external HTTPS RSS feeds then you may want to reconsider).

The problem with using it as a general solution is that not verifying peers when validating a certificate is akin to not using SSL at all - it opens the door to various SSL exploits.

The error is caused by the CMS environment not having any CA certificates available (fix detailed here: http://stackoverflow.com/questions/6400300/https-and-ssl3-get-server-certificatecertificate-verify-failed-ca-is-ok).
