### ISSUE TITLE
DataSets : dataset breaks after column 21

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1143]
When you add columns to the dataset it will be fine up to column 21, on column 22 it will show an error (unexpected error contact support).

`SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs Exception Type: PDOException`

If you close the form and refresh page, column 22 will be added, but it can't be deleted (not found) - it's not really there though after not found error, if you clear the browser cache it will disappear from web ui as well.

If I look in API call to GET columns in my dataset, it returns columns up to col21, it does not show col22 at all ie it's not actually there.

OP - https://community.xibo.org.uk/t/cannot-create-column-22-in-datasets---xibo-1-8-1/9669
It breaks on csv import probably for the same reason - it can't find it.

**Comment by dasgarner** [comment]
This is a 2 part issue - the first part being that adding the 22nd column fails - the second part being that the failure creates a broken database state.

The second part is the more pressing as the state is hard to recover from. Essentially the DDL statement to adjust the realised table causes the preceding transaction (i.e. the config adjustments) to be committed - the second part is fixed in #1151
