### ISSUE TITLE
How to enable thumbnails in layout?

### ISSUE THREAD

**Issue by knitehawk** [xibosignage/xibo#116]
How do i enable thumbnails in the layout. i have selected show thumbnails but it still doesn't show

**Comment by dasgarner** [comment]
The thumbnails are only applicable if the layout has a background image - if they don't show, then perhaps they dont?

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
