### ISSUE TITLE
server and client time sync

### ISSUE THREAD

**Issue by ygurdag** [xibosignage/xibo#123]
Is there an option to sync all clients time (clock) with server? So all clients can work with correct date and time.
Thanks

**Comment by nagyrobi** [comment]
I installed ntp on my xibo server, and installed an app called "NTPSync" on the Android boxes, which checks the time from the server and sets it every day (needs root).

**Comment by ygurdag** [comment]
Good Idea, what can I do for windows clients?

**Comment by andrew867** [comment]
This is what I use on my Windows clients:
https://www.meinbergglobal.com/english/sw/ntp.htm

**Comment by nagyrobi** [comment]
Yes exactly that here too.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
