### ISSUE TITLE
xibo server with Intel 3736F

### ISSUE THREAD

**Issue by TMAS-YEMEN** [xibosignage/xibo#134]
Hello guys,
I have a question,  does any body try to install xibo server in those new mini pc box that come with Intel 3736F & windows 8.1 , for example the new pipo X7 mini pc.

I want to use this device as server and player at the same time, any body can tell me if it will work or not!??

Thank u in advance,

**Comment by dkjain** [comment]
Hi,

I cannot say about the intel 3736F but I was able to run both server & client on Andriod TV box. MK809 III RK3188 Quad Core Android TV Box.

thanks
dkj

**Comment by dkjain** [comment]
Although it's possible but it wouldn't be simple though. You will have to do some research specific to your device hardware and software supported. Some things will work and some not. Pls note, Xibo is not an in-complex app and it's best to run on recommended devices if you are doing it for production or for your paying client.

thanks
dkj

**Comment by nagyrobi** [comment]
How did you run the server on Android?

**Comment by dkjain** [comment]
Palapa Web Server (search on play store) it's free.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
