### ISSUE TITLE
DataSets - lc_time_names is not correctly respected

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1410]
We would expect that when user changes `lc_time_names` in the database, that it will be correctly reflected in for example Formula column like `DATE_FORMAT('Date', '%a')` ie we would expect it to return the day name in the language set in the database.

That does not seem to work correctly, it is always returning those in English regardless of lc_time_names setting.

Docker installations seems to also reset it to the default en_US after stop/start up/down, as such we should investigate the issue further and fix it, then perhaps make the setting accessible from the web ui and handle the format / language code side without the need to directly interact with the database.

**Comment by dasgarner** [comment]
In principle we could have some "special syntax" for post processing a formula column in a DataSet after MySQL (i.e. PHP side) so that we could format the date with our PHP tools and leave the MySQL locale alone.

However, there doesn't appear to be a way to persist `lc_time_names` either in or out of Docker, so I question how this was working before and whether it is really a bug.

Also - setting lc_time_names per session does seem to work, e.g.:

```sql
mysql> select @@lc_time_names;
+-----------------+
| @@lc_time_names |
+-----------------+
| en_US           |
+-----------------+
1 row in set (0.00 sec)

mysql> set lc_time_names='es_MX';
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT DAYNAME('2010-01-01'), MONTHNAME('2010-01-01');
+-----------------------+-------------------------+
| DAYNAME('2010-01-01') | MONTHNAME('2010-01-01') |
+-----------------------+-------------------------+
| viernes               | enero                   |
+-----------------------+-------------------------+
1 row in set (0.00 sec)
```

Again, i'm not sure we really want to be doing that anyway.

Further clarification needed either way.

**Comment by PeterMis** [comment]
I seemed to work, at least to some extent as per the community topic where I've mentioned that before.

With that being said "special syntax" php side, if possible could be a better solution, in principle it would be good to give users an option to change the output language of the date via formula - we can follow this up on Friday!
