### ISSUE TITLE
libCEF.dll loaded with CEF switched off

### ISSUE THREAD

**Issue by jnko** [xibosignage/xibo#149]
Since upgrade to Xibo client 1.7.0 on Windoes 8 I often get this "Xibo has stopped working" notice.

The Client should display a simple and strict web page from my local webserver, containing jst a table.

Is there any option to enable logs in the client?

Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	XiboClient.exe
  Anwendungsversion:	2.0.0.0
  Anwendungszeitstempel:	54c69567
  Fehlermodulname:	libcef.DLL
  Fehlermodulversion:	3.1916.1804.0
  Fehlermodulzeitstempel:	53ea52cf
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	00156a80
  Betriebsystemversion:	6.3.9600.2.0.0.768.101
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	5861
  Zusatzinformation 2:	5861822e1919d7c014bbb064c64908b2
  Zusatzinformation 3:	84a0
  Zusatzinformation 4:	84a09ea102a12ee665c500221db8c9d6

Attached is a link to the html page.
https://gist.github.com/jnko/b6952c9f9a29f1cc62d7

**Comment by dasgarner** [comment]
Are you using the "CEF web browser" option?

**Comment by jnko** [comment]
Am 04.02.2015 um 14:41 schrieb Dan Garner:
> Are you using the "CEF web browser" option?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xibosignage/xibo/issues/149#issuecomment-72855596>.
> 

Yes and no ;-)
I used a plain Windows 8.1 x64, Xibo Client 1.7.0 with standardinstall.
I assume that CEF is enabled by default.

After the first crashes I thought I disabled by setting
<UseCefWebbrowser> to false in default.config
Well this had no effect at all.

Where can I disable CEF in Xibo or XiboPlayer?
How can I increase logging?


A side note: The issue above seems to occour only on one client,
a new factory default MSI WindBox mini PC.
Another testclient running Windows 7 seems to work normal.


Best
Joern
--

**Comment by Speedy-Gonzalez** [comment]
I'm not quite sure what you mean with "default.config". You should have a XiboClient.config.xml in your %APPDATA%\Roaming folder. But thats not the right way to change client options.

Since Xibo 1.7 the options for the client are managed in the CMS.

Go to "Display Settings" in your CMS. Add a new profile. Edit the new profile and go to the advanced tab. There is the option "Use CEF as the Web Browser".
After creating a profile it should normally not be activated. But you should try this and create a display profile for your displays.
Maybe without a profile the CEF Browser is used as the standard browser.

**Comment by dasgarner** [comment]
The default standard setting (if you don't create the display profile) is CEF = Off.

It is quite odd that libCEF.dll is loaded... I think I will need to look at that. I will tag this up appropriately.

**Comment by dasgarner** [comment]
Can you try the EXE linked to #36 ?
