### ISSUE TITLE
Add layout duration to the Layouts list and Designer

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#151]
Please add to the Layouts list a column with the computed total duration of each layout (taking in account all the regions duration), so the user can see them by looking at the table. Important to troubleshoot when layouts don't update because not expiring due to extra long durations set in certain regions.

Would be nice to see it in the designer page too, during modifying the regions, what's the total duration of the design.

**Comment by laercionit** [comment]
Usando o http://getid3.sourceforge.net/ acho que é possível obter a duração em minutos ou segundos do vídeo. 

$getID3 = new getID3;
$file = $getID3->analyze($filename);
echo("Duration: ".$file['playtime_string'].
        " / Dimensions: ".$file['video']['resolution_x']." wide by ".$file['video']['resolution_y']." tall".
        " / Filesize: ".$file['filesize']." bytes<br />");

**Comment by laercionit** [comment]
http://getid3.sourceforge.net/source/?t=structure.txt

Exemple: http://www.getid3.org/demo/

**Comment by dasgarner** [comment]
Yeah, we've used getID3 before (long ago)... its a big library and it's inclusion will need careful consideration.

**Comment by laercionit** [comment]
What is the reason you have removed this project library? It did not work well?

**Comment by dasgarner** [comment]
Well, it didn't seem necessary at the time - why bother working out the duration when you know you can do "end detect".

It was also not as good in the past (we are talking a long while ago)

**Comment by dkjain** [comment]
In addition to displaying the total duration, it would be great that total duration is editable i.e. modified / set by user that the layout should play upto. 

For e.g  A layout has 2 REGIONS
REGION-1 has 2 items equaling 120s 
REGION2 has 4 item equaling 300s. 
AFAIK, Currently Xibo will play the layout for 300s determined by REGION2, since that region has longest timeline.

What I propose is that there should be an additional "SET Play Duration " (or something similar) in layout action's list (drop down next to each layout) that when clicked opens a small form with computed total duration prefilled and that user should be able to modify i.e increase or decrease it.

Same could be extended to CAMPAIGNS. With total duration computed for every layout in that campaign and prefilled when user choose that option and should be able to modify i.e increase or decrease total duration.

What do u guys think ?

**Comment by dasgarner** [comment]
I don't see how that would work... what would it do if the durations were shorter or longer than the region durations?

**Comment by dkjain** [comment]
The user defined value should affect the region with the longest timeline. So if the timeline plays for 4mins (2 items each of 2mins) and user defined value is 3mins then the layout will play the first item for full length and the second item will play for 1 min and then the layout will end.

Is that difficult to implement, what could be the major block in implementing such a feature ?

**Comment by laercionit** [comment]
Really this layout term information is important. All sitemas of Mooh have this information. This helps the user better understand the system and how things work.

Could list the length by region and total duration of the Layout (= greater region)

**Comment by newburns** [comment]
So with this there is no need for loop until end on the Windows client? I'm assuming that option can be removed since it does not work. And you can play a region until the total layout time which will cause it to loop

**Comment by dasgarner** [comment]
I've answered your other issue, thanks.
