### ISSUE TITLE
DataSetView - templates needs adjustments

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1582]
Currently we're referencing column_1 in CSS in the provided templates via ((`td#col_1` `td#column_1` ), as we investigated that today, it would appear as the column_1 is actually the column with Row IDs and not the first column from the output, as such accessing and changing the CSS for it does not do anything.

We should ensure that column_1 is the first column in the output and then adjust the templates to reference column_1.

**Comment by brodkin** [comment]
Hey @PeterMis, @dasgarner, and @alexharrington, just a quick bit of feedback... 

We have a metric ton of Datasets with custom CSS for display, and this release broke all of them since our CSS selectors no longer matched. We had a hundred people surrounded by seven displays, and all of them looked terrible. Fortunately, I happened to be there at the moment and quickly edited down all of the CSS, but I would have liked to avoid the experience. 

I'm not sure how you guys version your releases, but I wasn't really prepared for a breaking change in a point release. Would you guys consider documenting how breaking changes are documented and released?

**Comment by dasgarner** [comment]
Hi @brodkin ,

Firstly apologies for the issue you had with this change - we completely understand and take on board your point of view.

It wasn't our intention to introduce a breaking change, and what happened was essentially a misunderstanding over the desired fix, which we have reverted and re-fixed (which might actually give you another problem if you upgrade again). The new fix contains the ID's referenced in the old way and classes referenced in the new way, to provide backwards compatibility.

With regards to how we release, the answer at the moment is that we don't have point/patch releases at all. This is something we recognise as sub-optimal and will be changing from 2.0.0 onward. I wrote about this earlier this year in the following blog post: https://blog.xibo.org.uk/releases-and-software-versions/

When we reach a stable 2.0.0 release, 1.8 will become bug fix only and from that point forward you can treat the .13, .14, .15, etc as point releases without breaking changes. Up until then we are grandfathered in to making feature changes in these release - 1.8.12 will contain feature changes.

More than happy to take any input you have into our new release process (as per the linked blog post). If you have any thoughts then you could comment on the article or open a new community topic.

Thanks

**Comment by brodkin** [comment]
Hey @dasgarner, no need to apologize! I both appreciate your commitment to semantic versioning going forward and the warning about the next point release. I'll ensure that I deploy it deliberately to avoid any issues. Also, thanks for being willing to listen!
