### ISSUE TITLE
Media Dashboard - improve the loading time

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1585]
Currently when we visit the media dashboard it will attempt to download all relevant data on the page load, which is increasing the page load time significantly on bigger CMS Instances.

We should ensure that it downloads the pages as we change them and that on initial load it loads only the 10 (by default) records ie first page only instead of everything.

**Comment by dasgarner** [comment]
There is a trade off to be had here which needs some thought.

We can switch to server side paging, but to do that the base of the query needs to be switched to widgets, rather than Layouts. I.e instead of saying "get me the Layouts this user can edit, and then enumerate those and expand their regions, playlists and widgets", we have to go from the other way "get me the widgets this user can edit, and back fill information about the layout/region/playlist they are on".

The upsides are that we can:
 - do paging
 - show users widgets they have permission to, on layouts they do not

The downsides are that we can't:
 - order by anything that isn't in the base widget query (i.e. not layout, region)
