### ISSUE TITLE
fonts.css module not downloading or building correctly

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1587]
platform: webOS

Symptoms: fonts.css is continuing to download data and is not assignable. Rebuilding the module does not resolve the issue. File size of fonts.css varies.

**Comment by dasgarner** [comment]
I think this can only be caused by concurrent cache regeneration (I am not sure what would trigger this - perhaps something on upgrade?)

Bottom line is that in all examples i've seen the MD5 on disk, in the media table and in RF is the same, but the file size is wrong between the media table and on disk. This means that the file size is wrong in RF, even thought the MD5 is correct.

This is particularly noticeable on webOS, because it checks the file size much more stringently than the others (which prefer MD5 over file size).
