### ISSUE TITLE
Xibo CMS 1.7 - Xibo API returning "The server with key "XXX" has already been registered" message

### ISSUE THREAD

**Issue by MichaelHoughton** [xibosignage/xibo#16]
When connecting to the Xibo API in 1.7, the message:

    "The server with key "XXX" has already been registered"

Even on a new database set up with no current users, this message still gets returned.

**Comment by dasgarner** [comment]
Hi - that sounds like an error from the API client end, rather than the CMS end. The error is raised when whichever client you are using (php oauth from the example project?) attempts to add a server to its list of connections.

You get the error because that should only be done once when the server is first registered.

If you take a look at your *client* database - any clear out the oauth tables, you should be able to start fresh.

**Comment by MichaelHoughton** [comment]
Hey Dan

Thanks for getting back to me.

The API is working in Version 1.6 and I am aware how it is meant to be working.

I dug a little deeper.  This was a FRESH install of 1.7 with a new database.  Basically, installed it, logged in, and set up a Application Token.

Once that is done, if you visit:
/services.php?service=rest

In the Xibo app, you get a white page, with the message:

    An upgrade is pending. Visit http://URL/xibo-cms/services.php.

I checked that message, and I could see the problem is, because my upgrade.php file is there.

This was told to be added when I first installed Xibo - but nothing since told me to delete it.

The problem we have, is that the application runs with upgrade.php, but the API checks it.  

Line 78 of xmds.php

    if (file_exists("upgrade.php")) {
        // An upgrade is in progress. Just quit since the server
        // won't be in a servicable state
       die("An upgrade is pending. Visit " . Kit::GetURL() . ".");
    }

It could be worth either removing this code, or removing the upgrade.php file after a successful install.

**Comment by dasgarner** [comment]
Hi Mike,

No problem - if it is a fresh installation, then we have an issue because `upgrade.php` has been removed in 1.7.0-rc1 (or at least it should have been). I'll have a check and see if/why it is still there - it isn't in the source any longer, that is for certain.

The internals of an upgrade in 1.7 series will be slightly different in order to provide a better user experience when upgrading (within the full CMS, by any admin user, etc).

In any case, you can safely delete that file from your root folder and hopefully that allows you to proceed.

**Comment by MichaelHoughton** [comment]
Thanks Dan - the installer looks for it at the initial step - you can't proceed without that file being created.

Thanks again.

**Comment by dasgarner** [comment]
You are entirely correct - how strange that didn't show up in the test installations (there have been many)! :)

I'll modify the install environment check so that it doesn't ask for that file any longer.
