### ISSUE TITLE
Security Vulnerability at Template and Resulotion page. 

### ISSUE THREAD

**Issue by bharatsewani1993** [xibosignage/xibo#1614]
**Steps to reproduce:** You should have two accounts one as Admin and other as a normal user account.
From the Admin account change user group permission and un-assign **Resolutions** and **Templates** permission under design menu section. Now login via normal user account and visit this URL:
(replace 127.0.0.1 according to your host/localhost).
http://127.0.0.1/xibocms/index.php?p=resolution&
http://127.0.0.1/xibocms/index.php?p=template&

Even though the user is unable to see the Resolution and Template menu Item in the menu, **he is able to access it via URL and can modify settings.** 

**version Tested: 1.7.10**
Able to reproduce this bug many times via different accounts, browsers and user groups. 

I made a fix for this in my local machine, please let me know If I need to push it live.

**Comment by alexharrington** [comment]
Thanks for your report.

Resolutions and Templates are both part of the Layouts page security setting, so the user correctly has access to those areas. The Menu security settings simply hide the menu from the user, but if they no longer have access to those areas then they won't be able to create or design layouts, since they need access to both resolutions (and potentially templates) in order to do so.

**Comment by dasgarner** [comment]
As Alex said, this isn't really a bug as it is intended behaviour (although you might say it isn't optimal). I will close this issue for now, if you'd like to discuss further please do so on our community forum.
