### ISSUE TITLE
Issue with webpages layouts

### ISSUE THREAD

**Issue by hsanchez08** [xibosignage/xibo#176]
Do you know if the problem when we put a layout with web pages, after six hours xibo client show me a message error with the application Microsoft .Net Framework, was resolved with the new version 1.7?

The message says:
Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue, If you click Quit, the application will close immediately.

Not enough storage is available to process this command.

I already have all version of .net framework installed, also I have Internet Explorer 8, and probe it with IE 9 and 10, but the message continues.

**Comment by dasgarner** [comment]
We do not have a solution to that problem yet - it appears that the memory leak in IE still exists in the new version.

This is a long running issue we have had with IE.

We tried to solve it with the CEF browser - but that has introduced some other issues.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
