### ISSUE TITLE
New Text media is missing the complimentary colour replacement tag

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [xibosignage/xibo#179]
After a fresh install the ck editor has a gray font color and a black background color. Not quite nice.

I've searched a little bit and found this (in theme/default/libraries/ckeditor/contents.css)

    color: #333;
    background-color: transparent;

Changes to that parameter work. You can see the result directly in Xibo.

I don't know how the moono skin from the ckeditor skins folder work but it seems not to override this settings from the contents.css

**Comment by nagyrobi** [comment]
+1 for this

**Comment by laercionit** [comment]
+1 for this

**Comment by dasgarner** [comment]
"ck editor has a gray font color and a black background color"

This is set by the JavaScript that loads the text editor - it is supposed to be a complimentary colour and depends on your background colour.

The bug is that the text field opens empty - it should open with a <p> that contains a replaceable #Color# tag

**Comment by Speedy-Gonzalez** [comment]
https://github.com/xibosignage/xibo-cms/pull/35
