### ISSUE TITLE
Dataset View Column Configuration is not saved.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1831]
CMS Version: 2.0.3

Issue: Create a Dataset. Now create a Layout and add the Dataset View Widget to it. When setting up the Widget, select the Columns you want to use and Save. When you return to the Configuration tab for the Widget, the Columns are no longer selected.

**Comment by PeterMis** [comment]
It looks like this condition - [datasetview-designer-javascript](https://github.com/xibosignage/xibo-cms/blob/release20/modules/datasetview-designer-javascript.twig#L48) is never true.

As such the dataSetColumnId is never set, so it's never sent on form submit, therefore the column selection is not saved for the widget.

``` $(this).find('form').data('formStep') ``` always comes as undefined in this case
the ```$(this)``` is basically not the form anymore at the point we try to test it - perhaps due to overlay while saving?

We could change it to be:
```
        let form = $("#dataSetViewEditForm2");
        if(form.data('formStep') === 2) {
```

That will work correctly for the edit on step2 and step1 will not be affected.

The same issue is true for chart and datasetticker javascript designer, however in their case, it does not seem to matter as the dataSetColumnId is set in different part of the code.
