### ISSUE TITLE
Unable to Load DLL Libcef

### ISSUE THREAD

**Issue by Andy2789** [xibosignage/xibo#190]
After upgrading Xibo to 1.7.1 CMS & Client to 1.7.0 on one of the clients an error message 'Unable to Load DLL 'LibCef' Exception from HRESULT 0XC000001D' This client is identical to another which works.

**Comment by dasgarner** [comment]
The player installation folder should contain libCef.dll - can you double check its there OK?

**Comment by Andy2789** [comment]
Yes, can confirm the LibCef.Dll is installed in the XiboPlayer folder, I have un-installed, re-installed several times. taken the LibCef.dll off another install and replaced. But makes no difference at all, it was running fine until upgraded to 1.7.0

**Comment by dasgarner** [comment]
I've built a version of the client EXE that doesn't reference that file at all (assuming CEF is disabled). I am hoping this will resolve your issue.

The EXE is [here](https://github.com/dasgarner/xibo-dotnetclient/blob/develop/bin/x86/Release/XiboClient.exe)

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
