### ISSUE TITLE
Dashboard Users Box

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#204]
Currently for providing content to multiple customers using a shared CMS.
The Dashboard is an important tool, but currently only the administrator uses.

I wonder if there is interest in showing the BOX Users, online users in the system. Currently show the total user, but I think the most interesting information is the total number of online users. It could be something as Users / Online

Ratify that is not important or impediment, but we could default the dashboard screen for all user if this adjustment is implemented.

I would be very happy to see this kind of implementation in version 1.8.

![image](https://cloud.githubusercontent.com/assets/325662/6119539/1a0926aa-b0b1-11e4-9bdc-603653854836.png)

**Comment by laercionit** [comment]
Doubt - Now Now showing

I looked in the manual and could not identify the exact definition of "Now showing" the Dashboard.

Total Layouts, Layouts Total scheduling, Now Playing (Default / Scheduling) ... many choices and questions ...

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
