### ISSUE TITLE
Unable to 'Preview Layout' in Internet Explorer

### ISSUE THREAD

**Issue by solane** [xibosignage/xibo#210]
IE opens another tab with the message 'Loading Layout' but just sits there and never actually loads the preview (see photo). The preview works in both chrome and firefox however on my network 
users only have IE installed.

Thanks
Sam

 ![ie issue](https://cloud.githubusercontent.com/assets/10942349/6128716/4d0a22b4-b130-11e4-866b-a6a8f75795d2.png)

**Comment by alexharrington** [comment]
The preview shows loading until it's been able to pre-cache all the media items associated with the layout so for some reason that's failing in your environment. It could well be because you're accessing via IP address and Internet Explorer is treating that as "Intranet zone". Please either exclude your IP address from Intranet zone so Xibo is treated as a proper website, or setup a FQDN for your Xibo instance and use that to access it.

**Comment by solane** [comment]
Thanks for the fast response however accessing xibo via FQDN doesn't fix the issue.

Are others having the same issue in IE or am I alone?

Sam

![ie issue 2](https://cloud.githubusercontent.com/assets/10942349/6129168/26e90556-b134-11e4-830e-24845d59ccde.png)

**Comment by alexharrington** [comment]
The screenshot shows a local name still so it will still be treated as intranet zone.

http://myserver.domain.com/xibo would be a FQDN.

I don't see this issue on IE

**Comment by solane** [comment]
Brilliant, works perfectly now.
Thanks
Sam
