### ISSUE TITLE
Windows client is not updating - newbie questions

### ISSUE THREAD

**Issue by MedusaDelft** [xibosignage/xibo#220]
First of all, I'm a newbie, so sorry if I ask obvious questions, but I can't find them in the documentation

I've created some layouts, but they don't seem to update on my Windows Client (CMS 1.7.1 / Client 1.7.0, Windows 8.1). I do see some javascript files and fonts etc. in my local temp-directory, but no text, no ticker, no clock is displayed. I do see an image and the background and the forecastio I've tried (btw, what a horrable layout). Is it a bug in the player, or am I doing something wrong?  

Also, from the first layout, I can't see the text I've entered in a text region. I also had problems using the font I've uploaded, but after two hours the font spontaneous appears in CKeditor.

The ticker seems to have an option 'background' but I can't figure out where this is set. Also, I can't change the font size and the font color. Is that correct?

I don't think github is the place to ask these kind of questions, but apparently according to Xibo this is the right place???

**Comment by MedusaDelft** [comment]
I've discovered that on the client-side, there were some files size '0'. So I've manually updated them and now it is working. I have not yet checked, but this might be a problem with uploading the zip-file to my hosting provider (binary/ascii upload?)

Other problems still exists :(

**Comment by Speedy-Gonzalez** [comment]
1. Player not updating content: Do you mean this problem with your second statement?
Have you added an display profile for your display? http://xibo.org.uk/manual/displays_settings.html. Maybe your update interval is too long. But the client should update its content on every program start.
2. Text not displaying in text field: Have you checked your font and background color. On a standard installation the background color is black and font color is dark gray, see #179.
3. I can't say anything to the ticker problem. Sorry.

**Comment by dasgarner** [comment]
It sounds to me like your player is unable to download some of the files it needs - the information screen (press i) will show you a list of files it is trying to download. You should never update player side files manually - you are masking a problem that will no-doubt reoccur.

The ticker - setting the background is an advanced operation that should only be done if you have manually adjusted the template and found that you need to add a background colour (say for example your ticker template produces artefacts - it may be because it doesn't like being transparent, so you can set a background colour in the advanced tab). Font sizing, etc is adjusted in the template - click override template and you can set them exactly as you want.

Regarding the font - this will have been your browser cache - the font form does say that you may need to clear your cache.

This is the correct place to ask questions - we do not have the "people power" to monitor more than one system.

**Comment by MedusaDelft** [comment]
I agree with you Dan that manual upgrading is never good. But I don't know the problem. At least it is showning something now. The 'I' screen (very hard to navigate through the long messages as the mouse is not showing!!). The message is not really helpful in fixing the problem. I still have not been clue!

The - Ticker: Dan, that is good information. Maybe you can add this to the manual (it's missing now, the picture in the manual doesn't show the 'background-color' option)? I also see a part of a dataset there (http://www.xibo.org.uk/manual/en/media_module_ticker.html)

I noticed the clear cache section. I tried clearing the cache. Several times in fact! Using IE and Chrome (both latest versions).

I do understand you want one place to ask questions. But sometimes issues are not shown (temporarely) or can not be found back at that time. Maybe it's a Git problem? But it is not helpful. Also everything is put in "one big pile" which makes it difficult to navigate/look at specific issues/search for issues. But that's just my point of view. I will use this issue tracker for now, no problem.

**Comment by Speedy-Gonzalez** [comment]
I haven't had any problems with issues yet. Maybe you should contact Github support.

**Comment by dasgarner** [comment]
@MedusaDelft we do what we can, I appreciate that the manual is not the best - but it is better and is getter better. If you would like to add those things to it, we would be more than happy to accept the contribution.

Regarding Issues - honestly I am not sure whether this place is the right solution or not. Launchpad Answers got in the way of the development process and I have already noted a big improvement in the collaboration of others since moving to GitHub (our first code contributions to the main CMS since 2006!). What GitHub issues does do is allow seamless transition between question, debugging, bug/enhancement and fix - which is what got my attention and what prompted the move.

Sure a forum might be better - but then I have to look in a forum and here and the code to answer one question... that is something we have tried before and don't want to go back to as it was horrible. The net result of having a forum was people never got answers, here they might be a little confused, but they will get an answer and a fix if there is a problem.

That being said, always happy to take suggestions for alternatives.

**Comment by MedusaDelft** [comment]
@dasgarner I'm happy you see the pros and cons. Good this works for you better than previous solution. I'm happy to help where I can.

About my problem: javascript files not downloading with an MD5-error. I've tried another computer on a different network. Same problem. I also noticed that the fonts.css file has the same problem. So maybe it's in the setup of my hostingprovider? Any idea what it can be?

**Comment by dasgarner** [comment]
The MD5 of each file is calculated and stored in the media table when the file is first uploaded. That MD5 is then compared to the file that eventually gets downloaded to the player application.

Those two checksums are not matched for some reason...

As you have tried another computer I would suggest that the MD5 is likely incorrect at the CMS end, rather than the player end. 

You could try running some SQL on the media table to clear all the cached MD5's (they will be regenerated). `UPDATE media SET MD5 = null;`

**Comment by MedusaDelft** [comment]
I've cleared the MD5's as instructed. I did see that most MD5's are recalculated, except for the  .js  files.
Running the client I get these new messages:

LibraryAgent|2015-02-17 11:11:18|Error|LibraryAgent - Run|Exception in Run: Could not find file 'C:\Users\Maurice\Documents\XiboLibrary\requiredFiles.xml'.
RequiredFilesAgentThread|2015-02-17 11:11:19|Error|RequiredFilesAgent - Run|Exception in Run: Input string was not in a correct format.

I suppose it has something to do with this?

**Comment by dasgarner** [comment]
The question is how did they get in the media table (and hence in the required files), but NOT in the library... that is very odd indeed.

Using the "Verify All" button on the Modules page should put them back where they should be.

**Comment by MedusaDelft** [comment]
Great, I did not know that. The 'verify all' seems to work!  I'll try the other display on the other network tomorrow to see if the problem is solved there too (I'm sure it is).

As of what it caused this problem: I have no clue. I've uploaded the complete program to my webserver and have not made changes to the files other than the Forecast IO (date-thingy) and today the CKeditor editor.css change (see other issue).  Maybe I did run the client before the upload or installation was finished?

**Comment by dasgarner** [comment]
Or we may have an installer bug - i'm not sure really - although if we do its not effecting every install.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
