### ISSUE TITLE
Enhancement: Set Bandwidth Limit on multiple Displays

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2201]
CMS Version: 2.3.3

Suggestion: Currently it is possible to set the bandwidth limit on individual Displays only. Suggestion is to add functionality that would allow a user to set a limit on multiple Displays at once.

**Comment by dasgarner** [comment]
Instead of our usual method of multi-selecting, which would mean calling the edit form for each display, I think we want a dedicated endpoint for this so that it can be called with an array of `displayIds` and a bandwidth limit. This will be much less intensive, but will need a tweak to the multi-select tool to accommodate.
