### ISSUE TITLE
Edit Profile location tab

### ISSUE THREAD

**Issue by andyblackham** [xibosignage/xibo#221]
When editing a display profile in Display Settings, the second tab is called Location, but the items within it are not location related.  They are Orientation and Screen dimensions.

The tab name and the contents do not seem to match up.

**Comment by dasgarner** [comment]
Its location on screen, rather than geographical location... although i'm happy to change it if you have a better term?

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
