### ISSUE TITLE
Widgets: make it easier to reuse HTML/CSS/JavaScript (developer experience)

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2214]
Global Setting for the `client.css` to make that easier to change - perhaps in addition to `client.css` actually as people may have that in their themes already.

**Comment by MarkCanada** [comment]
It'd be nice to set the CSS for a region for starters. I have a region with multiple DataSet Tickers and it gets cumbersome to have to copy/paste the CSS into each widget.

**Comment by dasgarner** [comment]
> I have a region with multiple DataSet Tickers and it gets cumbersome to have to copy/paste the CSS into each widget

If you had a way to easily save your css as a "template" (which you can use across all layouts/regions) and then just pick the template each time, would that make your life easier?

**Comment by MarkCanada** [comment]
> If you had a way to easily save your css as a "template" (which you can use across all layouts/regions) and then just pick the template each time, would that make your life easier?

Yes, it would. 
And it would be best if that template could be linked and update the selected tickers when the template is updated rather than have a template that can be used to manually push to selected items, but even that implementation would be a great time saver. 
And extra bonus points if (select) templates can be enabled cross-layouts as well.

**Comment by dasgarner** [comment]
That's good to know - we're working on exactly that capability as part of our v4 release.
