### ISSUE TITLE
Subplaylist Widget with Audio Tool does not play audio

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2382]
CMS Version:
2.3.8

Issue:
Create a playlist and add videos to that playlist. Now add that playlist to a layout using the subplaylist widget. Set a music file to play over the subplaylist using the Audio Layout Tool. When scheduled to a player the audio will not play.

Notes:
- The issue does not occur if you add the videos directly to the layout using the video widget.
- Tested on XfA R211 and XfW R256.

**Comment by dasgarner** [comment]
The behaviour here is correct because the sub-playlist widget is resolved to one or more widgets at build time, and it wouldn't appropriate to attach the audio to each of those individually.

We should prevent adding audio to a sub playlist widget.

 - [ ] API change to prevent adding audio to sub-playlist widget
 - [ ] UI change to remove the audio button from a sub-playlist widget
