### ISSUE TITLE
Use base container for Cypress testing instead of own container

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#2386]
We need to remove Dockerfile.cypress and use package.json Cypress dev dependecy in Dockerfile.ci instead.
 - Remove Dockerfile.cypress
 - Set specific Cypress version in package.json
 - Update Dockerfile.ci to **npm install** dev and not prod
 - Update test suite to use base container's  defined cypress version for testing

**Comment by dasgarner** [comment]
Turns out we can't use the base container for this, because the base container doesn't have node in it. There are two choices therefore - we install node in the base container, or we continue to use the separate cypress container, but with a named version in the dockerfile.

I think on balance it would be better to continue using the cypress container.
