### ISSUE TITLE
Assign Tab on adding a video or image is not working

### ISSUE THREAD

**Issue by mohamedirfan6186** [xibosignage/xibo#248]
Assign Option on adding a video or image is not working. Just stops there. But able to upload video or Image. Not able to assign. Do please Anybody help us to solve. Already i have raised a query but the reply i got is install again. Did the same but the issue persists. Can anyone please have a look on my configuration part through remote will be appreciated. Please try helping this out.

**Comment by andyrogers2012** [comment]
which version of Xibo are you installing 1.7.1?
if so when you re-installed did you re-download a fresh copy from xibo.org.uk or did you use your existing download?
The reason I ask is because their was a bug which was quickly patched and a new release of 1.7.1 had the fix in, but you would have needed to re-download a fresh copy.

Sounds like a similar issue to https://github.com/xibosignage/xibo/issues/186 , either re-download or replace the mentioned files in the linked bug a try again please

**Comment by mohamedirfan6186** [comment]
Thanks you so much.

 The latest patch rectified issue. Wonderful.

Appreciate for a quick response. Keep it up.

Thanks,
I Mohamed Irfan
