### ISSUE TITLE
Error on Versión 3.0.0-rc3

### ISSUE THREAD

**Issue by signodigital** [xibosignage/xibo#2504]
the effects in the ticker dataset no show the effect marquesin
<img width="659" alt="Captura de Pantalla 2021-05-11 a la(s) 20 09 52" src="https://user-images.githubusercontent.com/38365342/117903663-984d3500-b295-11eb-983a-29fa725511c8.png">
<img width="766" alt="Captura de Pantalla 2021-05-11 a la(s) 20 09 06" src="https://user-images.githubusercontent.com/38365342/117903668-98e5cb80-b295-11eb-8dc4-19340cb37f68.png">
<img width="750" alt="Captura de Pantalla 2021-05-11 a la(s) 20 08 44" src="https://user-images.githubusercontent.com/38365342/117903674-997e6200-b295-11eb-9a0c-c89667ab0699.png">
an sometime aparece un error de conexion al sql state esto pasa al programar en schedule pero en layout al programar no aparee ese error

<img width="802" alt="Captura de Pantalla 2021-05-11 a la(s) 20 28 44" src="https://user-images.githubusercontent.com/38365342/117904788-a00dd900-b297-11eb-8861-8e9151573c99.png">
<img width="433" alt="Captura de Pantalla 2021-05-11 a la(s) 20 18 49" src="https://user-images.githubusercontent.com/38365342/117904789-a00dd900-b297-11eb-93bb-12a54c06d479.png">

**Comment by dasgarner** [comment]
Hi and thank you for reporting this issue!

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this support request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
