### ISSUE TITLE
How to Become Contributor For Translating Xibo

### ISSUE THREAD

**Issue by asrarak** [xibosignage/xibo#252]
Halo, how can i become contributor for translating Xibo?

**Comment by dasgarner** [comment]
Hi,

Translations are all managed on [Launchpad Translations](https://translations.launchpad.net/xibo), so all you need to do is create an account and start translating using the web UI.

Alternatively (if you prefer PO files) you can download the POT file from the xibosignage/xibo-cms repository and then request / upload translations in Launchpad.

Thanks for the offer!
Dan

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
