### ISSUE TITLE
Layout Designer : Topbar actions submenu

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#2522]
With  the addition of Interactive Actions to the Layouts in v3, the dropdown in Layout Designer topbar also called Actions, can cause some unnecessary confusion.

We should either rename that submenu dropdown (to just `Menu` perhaps? ) or replace it with a suitable icon.

The `Discard Layout` option should be renamed to `Discard draft` to avoid potential confusion with what it does.
(we do already have a confirmation popup describing what it does once clicked)

**Comment by dasgarner** [comment]
> replace it with a suitable icon

The consensus is the burger menu as that is easily recognisable.

**Comment by maurofmferrao** [comment]
## **Update on Toolbar actions menu!**

I decided to simplify the menu colours since we're going to use the same menu for Layout actions and Editor options.

Published layout:
![new_menu](https://user-images.githubusercontent.com/18596680/121508057-1f004980-c9dd-11eb-8260-affbebcf95af.png)

Draft layout:
![new_menu2](https://user-images.githubusercontent.com/18596680/121508176-3d664500-c9dd-11eb-9b1c-abc373322479.png)

Playlist editor:
![new_menu3](https://user-images.githubusercontent.com/18596680/121508251-4eaf5180-c9dd-11eb-8ef8-341053e695c2.png)
