### ISSUE TITLE
Name Filter : do not use space as a delimiter for searching

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#2526]
While powerful, current way of filtering results by name, can be confusing to Users.

We should continue to separate search terms by `,`  and no longer separate each term by ` (space)`  as well.

**Comment by PietroPizzi69** [comment]
Sorry, but any User who knows google f.e. would disagree on this one. I can't think of an example where a non-programmer experienced such a strange search method (and even worse because the terms are OR'ed).

This change is a real PITB!
https://community.xibo.org.uk/t/how-can-i-filter-dynamic-displays-groups-with-and-search-terms-like-a-b-c/27226

**Comment by dasgarner** [comment]
I am sorry this doesn't work the way you want it to, but it was changed as a direct result of feedback from end users. If you would like to propose a change or extension to the way filtering works, please do so over on the community forum. Thank you.
