### ISSUE TITLE
Media type Video also shows layouts

### ISSUE THREAD

**Issue by andyblackham** [xibosignage/xibo#254]
When I click into Library / Media, I also see Layouts.

This is confusing, makes the content list very long and cannot be filtered.
So I cannot pick out the specific videos I have uploaded from the much larger number of layouts that contain them.

Is this deliberate behaviour?
Id like to not see layout items in media.
If they must stay, then I really need the ability to filter them.
Wouldn't they be better categorised as Layouts in this view?

**Comment by dasgarner** [comment]
Layout are not shown in the library page - they should only appear on the Layouts page. So i'm afraid that I don't know what you mean...

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
