### ISSUE TITLE
new dataset update on dataset Ticker don't link properly

### ISSUE THREAD

**Issue by veenone** [xibosignage/xibo#2551]
Hi all,

I have an issue with **dataSetTicker**.
I made an update of a dataset linked to dataset ticker region.
In this region I'm using the template according to the updated dataset.
However the updated dataset is not listed in this snippet dropdown

![image](https://user-images.githubusercontent.com/3839381/123940301-3a022000-d9c3-11eb-99f0-a5b45b0ddf48.png)

but my template string has already the string for the new snippet in [col_name|col_id] format,

it seems like the dataset and widget doesn't linked properly.

it doesn't happen if I create a new datasetTicker widget (manually). the snippet dropdown will be populated with the dataset columns.

Additional information :  currently I'm using xibo CMS **2.2.2**

**Comment by PeterMis** [comment]
Hi and thank you for reporting this issue!

Xibo's development team use Github for verified bug reports and feature specifications only. 

That said, it should be just the case of refreshing the Layout Designer either by refreshing the page or saving the Widget, which will reload it and fetch dataSet columns, which should be available in Snippets for you.

If that's not the case, please can you direct this support request to our [Community ](https://community.xibo.org.uk/)so that it can be looked at by the team, or our great community, when they can.

Thanks!
