### ISSUE TITLE
Synchronised Content: Sync Groups and Schedules

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2574]
Add sync groups and schedules to support synchronised content.

**Comment by alexharrington** [comment]
I wonder if the CMS can collate and send IP addresses for the sync group - even if those are just used as a starting point for discovery? I know we shied away from that before because of the specific environments those were going to be used in, but it might simplify somewhat? If the nodes can pass on the IPs of others they know about, then as long as one IP in the list that a new player gets is still valid, then there's no need for discovery?
