### ISSUE TITLE
Implement Server Side Paging

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#258]
Currently have 5800 files in the library, small files, to give more details, the amount is only 40GB.

By clicking on media, this taking too long to list the contents, about 20 seconds. Have analyzed the apache server, disk IO and database,  I did not find problem.

I do not know if it's a matter of index paging or code setting.
Dan, could confirm this scenario what can be?

I realize that it takes too long to load, but when changing paging, will very quickly, which indicates that all content was returned regardless of what is shown.

In my opinion it would be more interesting to quickly open the screen and change as the paging load the next items, similar to image search on google or facebook navigation.

Below the link of a video showing the possible problem, hope it helps:
https://www.youtube.com/watch?v=aRhIcrHMSIQ&feature=youtu.be&hd=1

**Comment by dasgarner** [comment]
You are correct that all items are returned and then paged accordingly, rather than submitting new requests with each page action.

It is done that way because of a nice paging and table sorting library - no other reason.

The library was updated recently to have the capability to load pages in via AJAX, but we have not yet taken advantage of it.

It is one of the blueprints we will migrate from Launchpad when we get some time.

**Comment by laercionit** [comment]
Any predictions to implement this improvement?
It really is a bad situation that takes every click the library.

At the moment we do not have timeout, but continue to increase we can begin to receive timeout in MySQL or Apache.

**Comment by dasgarner** [comment]
I've tagged this up for you.

I'm really not sure when it would be completed as it is potentially a big job which only effects a few people (people with very large libraries).
