### ISSUE TITLE
Cas Authentification error

### ISSUE THREAD

**Issue by Tony-Jab** [xibosignage/xibo#2618]
Hi,
I just upgraded Xibo to version 3 and CAS authentication doesn’t work anymore.
When I click on “CAS Login” button, I get “Error : Internal script failure”.

**Comment by PeterMis** [comment]
Thank you for bringing this to our attention. 

I believe it only needs a small adjustment on phpCAS client creation, to ensure that the port is a number not a string.

In the meantime, you could also fix it by making a small change in your settings-custom.php file, where the CAS Middleware is initialised.

Let's take the example from our documentation ie
```
$authentication = new \Xibo\Middleware\CASAuthentication();
$casSettings = array(
    'config' => array (
        'server' => 'your.cas.server',
        'port' => '443',
        'uri' => '/cas'
    )
);
```

If you were to change the `port` value to be a number instead of a string ie for the same example:
```
$authentication = new \Xibo\Middleware\CASAuthentication();
$casSettings = array(
    'config' => array (
        'server' => 'your.cas.server',
        'port' => 443,
        'uri' => '/cas'
    )
);
```

That should do the trick as well, in version 2 we were explicitly making sure that port value is an integer, however in v3 that part is missing - will be fixed in the next release.

Please do let us know if that change fixed it for you.

**Comment by Tony-Jab** [comment]
Hi,
Indeed it’s works :). Thanks for your answer.
Tony
