### ISSUE TITLE
No reports in "Proof of Play" 

### ISSUE THREAD

**Issue by Azhdar1990** [xibosignage/xibo#2652]
Hello

**Issue**

I’m having trouble trying to use proof of play reporting. 
I’ve followed all the steps to enable reporting:
IN:
library/Media: I've set on all my media "Enable Media Stats Collection?" - ON
design/Layout: I've set on layout "Enable Stats Collection?" - ON
displays/Display Setting Profiles: I've set on windows "Enable stats reporting?" - ON ; Aggregation level - individual
administration/settings/displays:  I've set "Aggregation level"- individual; "Enable Stats Collection?"- ON; "Enable Layout Stats Collection?"- ON; "Enable Media Stats Collection?"- ON; "Enable Playlist Stats Collection?"- ON; "Enable Widget Stats Collection?"- ON; 

My layout total duration is : 2 min, 22 sec.

I've created this layout on 11.11.2021 12:00.

But still there is no data at all from the player. 
All "Proof of Play" reports are empty. 
Please could you help how to resolve this issue? 
Thanks in advance.

**Xibo Digital Signage Version**
3.0.3  (DOCKER)

**Player Type**
Windows

**Player Version**
xibo-client-v1.8.14-win32-x86

**OS**
Windows 8.1 Pro (Ru)

**Comment by dasgarner** [comment]
Hi and thank you for reporting this issue!

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this support request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!

**Comment by Azhdar1990** [comment]
Okey thanks
