### ISSUE TITLE
CR: Dataset View map function

### ISSUE THREAD

**Issue by Digitum** [xibosignage/xibo#2679]
Change request.
Add possibility to add a map function to dataset array on view. The javascript function is user provided and should apply on the javascript Array map method, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map .
Also, pass an empty thisArg object to be able to store data between the iterations.

Example:
Provided dataset as Javascript Array:
```
[
  {company: "ACME Inc", floor: 1},
  {company: "The Big Company Inc", floor: 1},
  {company: "Small business Inc", floor: 1},
  {company: "Second Floor enterprises Inc", floor: 2},
  {company: "You Ghurt Inc", floor: 2},
  {company: "Nevermind Business Inc", floor: 3}
]

```
For example, write a map function:
```
function(element, index, array) {
  // Initiate lastFloor on "this" object
  if(!this.lastFloor) {
    this.lastFloor = null;
  }
  
  // Create new data item with added floor data. If current items floor information is equal 
  // to last items floor information (from thisArg) , then we does not set floorTitle 
  // information. If not same, then we show floorTitle information set to the new floor.
  
  var data = {
    company: element.company,
    floor: element.floor,
    floorTitle: element.floor === this.lastFloor ? '' : element.floor;
  }
  
  // Set thisArg lastFloor to this elements floor.
  this.lastFloor = element.floor;
  // Return the data to the new mapped array
  return data;
}
```
This will result in following array list:
```
[
  {company: "ACME Inc", floor: 1, floorTitle: 1},
  {company: "The Big Company Inc", floor: 1, floorTitle: ''},
  {company: "Small business Inc", floor: 1, floorTitle: ''},
  {company: "Second Floor enterprises Inc", floor: 2, floorTitle: 2},
  {company: "You Ghurt Inc", floor: 2, floorTitle: ''},
  {company: "Nevermind Business Inc", floor: 3, floorTitle: 3}
]

```
This makes the company legend in the buildings entrance much better look.

My suggestion is that this map function shall apply on data after order and filtering data with current functions. Any item that returns undefined or null shall be filtered out from the list.

As an alternative, let it be possible to provide a named map function, for example `datasetMapFunction` that is used when defined.
![image](https://user-images.githubusercontent.com/9963291/145442014-d67f5e8e-0bbe-4165-a49b-b62494848229.png)

Edit: Maybe two functions should be implemented, one that applies on data before pagination, and one that applies on data after pagination. Othervise there could be unvanted issues in pagination,

**Comment by dasgarner** [comment]
Hi and thank you for writing up this feature request.

We're having a big push towards developer experience in the next major Xibo release, and this will be useful for us to feed into those design decisions. 

It would be much appreciated if you direct this idea to our [Community](https://community.xibo.org.uk) in the "Features" section so that it can be looked at by the team.

It would be quite challenging to address your requirements in the way that you suggest, because the DataSetView Widget outputs the HTML for the data table and not the raw items. When you add your feature request to community it would be useful to include **what** you're trying to achieve as well as a link back here which shows _how_ you think we should do it.

Thanks!
