### ISSUE TITLE
calling on datasets from other areas.

### ISSUE THREAD

**Issue by solutionssquad** [xibosignage/xibo#271]
Is it possible to call a dataset from a different module?
For example, I have a webpage url that loads on multiple displays, that needs changed from time to time.
If it was possible to load it from a centralized place, like a dataset, I wouldn't have to edit all the layouts to update it each time.

Thanks!

**Comment by dasgarner** [comment]
you could create a ticker item which only displayed the relevant item from the dataset and created an iframe out of the dataset which showed your webpage.

But no - not in an automated fashion as it would mean that the dataset governed the structure of the XLF itself, rather than the rendering of a particular media item.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
