### ISSUE TITLE
Unable to view or edit an event in the schedule I created

### ISSUE THREAD

**Issue by NunzioArdi** [xibosignage/xibo#2748]
(I use a translator, sorry)
Hello, 
There is a problem with the schedule. When I create an event, once done, I can't edit it or even see it. It appears in "View Only". The only way to be able to interact with it is to be "Super Admin", otherwise, no matter what, it does not work.

Couldn't he have a dedicated role to control the calendar?

Thanks

Translated with www.DeepL.com/Translator (free version)

**Comment by dasgarner** [comment]
Hi and thank you for reporting this issue!

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this support request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
