### ISSUE TITLE
Random Widget each cycle is picking a random entry from the playlist

### ISSUE THREAD

**Issue by Hojosa** [xibosignage/xibo#2775]
using the sub-playlist with random widget each cycle, items from the playlist are displayed in their order, and not random. 

Settings Used:

*Playlist(Jokes): Dynamic, inherit, filter -> name filter "joke" result are 37 different images
*Sub-Playlist Widget in Layout 
         General -> Playlist Jokes, 1, 5, Fill
         Config -> Auto, Add, Enable cycle, play count 2, random

Expected behaviour: displaying 1 item from the playlist in each slot, order random
What happens: displays the first item from the playlist in slot 1 and the second item from the playlist in slot 2

**Comment by dasgarner** [comment]
Hi and thank you for reporting this issue!

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this support request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

As a side note, please make sure you're running a Player which supports cycle playback (the latest windows/android players do).

Thanks!
