### ISSUE TITLE
Xibo CMS 3.1.0 API issue - The JWT string must have two dots

### ISSUE THREAD

**Issue by DarkAllMan** [xibosignage/xibo#2778]
Since updating to 3.1.0 I have an issue connecting the API.
Via Postman I can get the token, but any other API request results in:
`{
    "error": "access_denied",
    "error_description": "The resource owner or authorization server denied the request.",
    "hint": "Access token has been revoked",
    "message": "The resource owner or authorization server denied the request."
}`

Can anyone confirm this behaviour?

**Comment by dasgarner** [comment]
This doesn't appear to be a general issue with the API as it works on our test servers and on a default docker installation.

3.1 puts access tokens in a server side cache so that they can be revoked in case of a security breach - maybe your cache isn't working.

Please can you direct this our [Community Dev Category](https://community.xibo.org.uk/c/dev/12) so that someone can dig into the details with you? Feel free to link back here so we can track the issue if it does become a verified bug. :bug: 

Thanks!

**Comment by dasgarner** [comment]
I'll take a quick look now for you, but if it isn't obvious you'll have to be patient i'm afraid, we're all juggling lots of different things :juggling_person:
