### ISSUE TITLE
Default image in layouts/templates after migration

### ISSUE THREAD

**Issue by oteixido** [xibosignage/xibo#2780]
After migration from CMS 3.0.6 to 3.1.0, thumbnails of layouts and templates disappear and the image "theme/default/img/thumbs/placeholder.png" is showed. 

If I click the default image, then a message "Add Thumbnail" appears. When I click this message, a popup appears with the text "Failed to load image: /layout/thumbnail/233".

**Comment by dasgarner** [comment]
Hi and thank you for reporting this issue!

I'm really sorry I didn't see it sooner.

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this support request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
