### ISSUE TITLE
Flash Player Pops up New Window

### ISSUE THREAD

**Issue by necouchman** [xibosignage/xibo#280]
I'm running Xibo Server 1.6.3; client 1.6.0-rc2. I'm seeing an issue that I've seen a couple of people mention where Flash content is not being displayed embedded in the client, but starts in a new window. In particular, I'm trying to embed Ustream.tv content, which (apprently) requires either the flash plugin or a dedicate app. It seems like they might have some sort of HTML5 client that doesn't require a plugin, but only for Smart Phones? Anyway, when I embed the video from Ustream.tv it shows up as a new window.

I'm seeing this on two different systems:
- Ubuntu 12.04 32-bit, Dell Precision with nVidia Graphics card.
- Ubuntu 14.04 64-bit, LIVA Mini-PC with Intel HD Graphics card.

Any hints as to how to get this to embed properly would be appreciated; or, alternatively, how to force Ustream to use flashless video technology.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
