### ISSUE TITLE
Refresh page in CMS after adding new display

### ISSUE THREAD

**Issue by loosus** [xibosignage/xibo#2948]
I am not sure if this is a bug or a feature request, but it's fooled enough people on our side to warrant saying something: when you add a new display in the CMS, the page should immediately thereafter refresh to show the new display.  Currently, it gives the impression that a new display has not been added, when it actually has been.

Repo:

1. Install the Xibo Player for Windows.
2. When the player appears, use the code option.
3. Browse the CMS in Google Chrome.
4. Click "Displays."
5. Click "Add Display (Code)."
6. Input the code provided by the Xibo Player for Windows.
7. Click "Save."

The display will be added, but it won't immediately appear in the list of displays until the user manually refreshes the page.  Nowadays, I believe this would be considered unexpected behavior because users are used to auto-refreshing pages.

**Comment by dasgarner** [comment]
Thanks for the feedback - the reason it isn't displayed immediately is because it isn't immediately added. Adding by code tells our auth service that the display should configure itself against your CMS the next time it validates its auth code, which can be up to 10 seconds from the time you save it.

I do understand why this causes confusion and we will give it some thought. In the mean time please can I direct you to our [Community](https://community.xibo.org.uk) for feedback in the future.

Thanks!
