### ISSUE TITLE
MySQL proof of play records cannot not be sent to the Audience API

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3009]
When using MySQL as the primary source for stat records and sending them to the Audience API, the following error occurs:

`General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. Exception Type: PDOException`

**Comment by ifarzana** [comment]
This error occurs when attempting to execute a query while another query is still in progress. The error is indicating that there are multiple active queries and one of them is unbuffered. 


- MySqlTimeSeriesStore getStats() method uses MYSQL_ATTR_USE_BUFFERED_QUERY to `false` (https://github.com/xibosignage/xibo-cms/blob/develop/lib/Storage/MySqlTimeSeriesStore.php#L429) that is why a second query to get a campaign returns the above error.

`MYSQL_ATTR_USE_BUFFERED_QUERY `constant stores the result of a database query in memory on the client side. 

To resolve this we have to set the constant to `true`

Can you give your input on that, @dasgarner ?

**Comment by dasgarner** [comment]
From memory we set `MYSQL_ATTR_USE_BUFFERED_QUERY` to `false` so that when we're exporting or archiving a huge number of stats in a single query, they are not buffered by MySQL, which helps manage the MySQL memory usage.

In the case of our audience sync, where we always set a row limit on the return, we should be OK to use the default setting, which is to say `true`.

Passing in an option so that we can disable this would be sensible and solve this issue.

**Comment by dasgarner** [comment]
This is difficult to test because develop, staging and the whole of cloud are MongoDB, and a local CMS is not straightforward to get configured with a player and audience connector.

Instead I tested the _logic_ of what has been done with a simple script that opened a buffered vs non buffered connection.

Therefore I think this is ✅
