### ISSUE TITLE
send commands from xibo server

### ISSUE THREAD

**Issue by martialgallorini** [xibosignage/xibo#301]
Hello,

it could be interesting to allow the xibo server to launch scripts locally instead from telling clients to do so.

for example, some of my clients are connected to video projectors. for reliability reasons, the projectors should be turned on before the client pc turns on, otherwise the client can have problem detecting the projector.

in that case, xibo server could send the POWER ON to the projectors and then send wakeonlan packet to power on the computers once projectors are on.

thanks

**Comment by dasgarner** [comment]
I don't think we want to introduce an dependency on the CMS pushing data out to the players - i'm uncomfortable with the support overhead that would come with that.

Why wouldn't you just have another application to manage switching on both devices in order?

**Comment by martialgallorini** [comment]
I can use another app to do it but... yeah it is another app, again ! ;)

But is there any dependency involved ?
In my thought i imagined i could have a field where i could enter a local command executed by the server. That command would be Windows, mac or linux dependant but nothing to deal with the CMS.
Maybe i a wrong.

That was just an idea that someone might share.
If dependencies are involved, then i understand your position and that make sense.

Thank you.

**Comment by dasgarner** [comment]
Of course, technically it would be possible... but it effectively means opening up the command line of the web server to arbitrary commands, or providing a list of common commands - which wont work on 90% of systems because they wont have access to the command, or their server wont have a direct route to the player or because the command wont be in our list.

For me its a "principle" thing - a web application shouldn't be pushing commands around the local network or running anything in the shell of the server.

Setting up CRON to do it would be simpler and safer IMO... but I will leave this open incase there are a lot of up votes.

**Comment by martialgallorini** [comment]
i share your "principle" ;)
but talking about command access, i imagined this is up to the server administrator to manage this, not to the CMS. Same thing for the client if i remember (i only used python client so far).

**Comment by dasgarner** [comment]
I think nervous is the word - a lot of people using Xibo aren't sysadmins, they are people with shared hosting (most likely without exec permissions I admit).

Shell commands in the player are far more isolated, although I will also admit people could do some damage if they weren't mindful.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
