### ISSUE TITLE
Issue with Touch/Click Actions in Layouts

### ISSUE THREAD

**Issue by mmaxwell5** [xibosignage/xibo#3015]
I am experiencing an issue where v3 R307 client is crashing sporadically when our layout contains click/touch actions.    If we remove all click/touch actions our layouts work fine.  If we add them, the client goes to the "XIBO Open Source Digital Signage" screen and will sometime crash the whole player.

**Comment by dasgarner** [comment]
Hi and thank you for reporting this issue!

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this support request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
