### ISSUE TITLE
Flash file stop play and disappears

### ISSUE THREAD

**Issue by Carlos-Costa** [xibosignage/xibo#302]
XIBO 1.7.1 - Use CEF as the Web Browser - WINDOWS CLIENT 

When a layout refresh, the file in flash stop play and disappears

Any solution?

**Comment by Carlos-Costa** [comment]
Hi Dan, can you help me with this?

**Comment by Carlos-Costa** [comment]
HELLO... ANYONE  PLEASE.....

**Comment by dasgarner** [comment]
Please turn CEF Off and try again

Shouting for help and emailing me is not the way to go about it... we reply to all messages from the community when we can - time permitting.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
