### ISSUE TITLE
Widgets: Add the ability to filter datasets by display tag

### ISSUE THREAD

**Issue by harbormw** [xibosignage/xibo#3062]
Maybe i'm missing how to do this -- I see we can filter by DisplayID -- but the incoming dataset has no awareness of DisplayID -- but we do have store locations.

What I'm looking to do is have one layout, which filters and displays only rows that match a "store number" attribute in the data set -- based on a named-tag for the display its rendering on.

So an example would be a display with tag "store: 1256" -- and in the filter for the dataset view i'd like to be able to include in the SQL something like [tag=store:1256] or the like to further filter the data set at the player level.

Am I missing something or is this feature not present currently?

**Comment by dasgarner** [comment]
This feature isn't present currently.

v4 does make the [tags set on a display available to the player](https://github.com/xibosignage/xibo/issues/2773) although we are not using that functionality for anything as yet.

I think in this case you'd want that filtering to happen on the CMS? So that you could create a filter which uses a variable to populate the tag, something like `[Tag:StoreNo]`?

We'd appreciate it if feature requests / questions went into the [Community](https://community.xibo.org.uk) please. Xibo's development team use Github for verified bugs and road mapped features only.

Thanks!
