### ISSUE TITLE
Problem with Xibo Player 4 R401.0

### ISSUE THREAD

**Issue by jeremy-smits** [xibosignage/xibo#3189]
Hello,
Since updating my server to version 3.0.8 > 4.0.4 the Windows client no longer works.

To summarize, I was in CMS version 3.0.8 and I upgraded to version 4.0.4.
I also updated the php version as requested to a minimum PHP version 8.1, so I went from a version 7.4.10 to 8.2.11.
Since the update, I only get this message on my clients with the latest version 4 R401.0 application.

On the server side, I access it well and I don't get any error messages.

Here is the error message I get:

"
Status
The client found 'text/plain;charset=UTF-8' as the response content type, when it expected 'text/xml'.
The request failed with the error message:
"

**Comment by dasgarner** [comment]
Hi and thank you for getting in touch. 

It looks like this might be a support request.

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
