### ISSUE TITLE
XMDS: missing default layout throws HTTP 500

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3201]
The error message in the log is:

```
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column xibo_triple-it_nl.display.defaultLayoutId at row 1
```

Points to consider:
 - is it right to throw an error here? Or should we log an error but still succeed?
 - whether we throw or log, the message should be more specific

**Comment by PeterMis** [comment]
Related potential issue is that the Settings page may appear as a Layout is set as default, however the table may just have an empty value for that setting.

This is due to the getById function in Layout Factory, it will not filter layouts at all and just return the first entry if we pass an empty string to the getById - which, while unlikely, is possible on Settings page if the value for `DEFAULT_LAYOUT` is an empty string.

We probably want `if (empty($layoutId))` instead of `if ($layoutId == 0)` there to protect against it.

**Comment by dasgarner** [comment]
:white_check_mark: tested
