### ISSUE TITLE
Preview layout function seems to be broken and does not render all elements

### ISSUE THREAD

**Issue by Maxouuz** [xibosignage/xibo#3254]
We noticed, since an update from v3.1.4 to v4.0.5, that every items added in the layout editor (examples : text areas, images or from time to time clock widget) were not displayed or rendered. Most of the time, background image is always displayed in the preview window but others are missing. The problem only occurs in the preview layout rendering : display on broadcast screens is OK.

We tried to create new templates from scratch with no luck, tried to add every item in a canvas and we even install the entire stack on a new virtual machine without success : the problem still occurs. Any advice on how to fix this ? Should we downgrade ? 
![image](https://github.com/xibosignage/xibo/assets/92172846/3e9f4d2f-73a7-4434-9e26-135c849e7808)
![image2(1)](https://github.com/xibosignage/xibo/assets/92172846/ac23e3a2-86fd-4f4e-b47e-45aac61cbc18)

@mmasquelin

**Comment by dasgarner** [comment]
We're aware of some problems with previewing which are being addressed in the up coming 4.0.6 release. If you'd like to have your specific examples tried out, please do create a topic on our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
