### ISSUE TITLE
Do we need a forum?

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#332]
There have been a number of requests for a forum recently and we would like to weigh up the pros and cons of using a forum system in addition to GitHub Issues.

### Our pros
 - GitHub for Issues and only issues means less clutter
 - A forum would present a less technical appearance to end users
 - Community members could take a more active roll in the forum with moderation capabilities

### Our cons
 - We have limited resources, monitoring 2 systems instead of 1 will stretch these resources
 - Hosting cost implications (GitHub is free, servers to run forums are not)
 - When we had a forum before we spent all our time saying please report that over here, or this over there as people put things in the wrong place.

Opinions and feedback are welcome!

**Comment by mrweekender** [comment]
https://www.proboards.com/

**Comment by newburns** [comment]
I say you do not have a forum..... HOWEVER, just know that every little thing submitted is a bug.
Nothing can be small because there are no real easy ways to look at solved issues that may be small.
Such as 1.6.4 upgrade to 1.7.0 mysql error, that was reported a billion times, but solved in the issues.

**Comment by mrweekender** [comment]
A forum would provide a place for common resolutions to known issues, through the use of stickies or moderator editable areas.

**Comment by nagyrobi** [comment]
+1 for a forum

**Comment by JianjianHuang** [comment]
It's hard to determine if the question is really a issue. May I have a suggestion? let's stay here, but when we report something, we put a prefix in the title.
For example:
Issue:xxxxxx
Suggestion:xxxxxx
Question:xxxxxx
Discussion:xxxxxxxx

**Comment by dasgarner** [comment]
@JianjianHuang that would be great in an ideal world - but I think 90% of visitors would not follow the criteria

@mrweekender would a forum solve that problem? there would have been 1 "issue" here in github which was the bug fixing the upgrade problem, and then a billion forum threads

Just to be clear - we believe that GitHub provides the best platform for tracking bugs and managing development and we wouldn't move that (it is working **great**). If we had a forum **most** people wouldn't have need to come here as support issues would be handled on it.

**Comment by Speedy-Gonzalez** [comment]
Maybe we should start to use the [wiki](https://github.com/xibosignage/xibo/wiki) for "stickies" or FAQs.

**Comment by MedusaDelft** [comment]
Please keep the documentation, "stickies" or FAQ's in one place and not at a couple different places. It's difficult enough to see answers and more in-dept explanations here in open/closes issues and having a look at the documentation in another place.
Also PLEASE feel free to enrich the current documentation with your FAQ's or "stickies"!!  (I should do so myself!).

I don't know what the plans are for milestone 1.8 (except 'interactive signage' and cross-browser player --> very useful, looking at Raspberry PI currently for a customer), but animating xibo-content more easily should be also a next big thing, because support is rather poor to be honest while other siginage-solutions do have animation possibilities (fade between layers, slide in content, images on show (can only be done now by writing own css-stuff as regions overlap).

The reason I mention this is that if animation will be next, a lot more questions will be asked. Maybe even 'interactive signage' will give a lot of questions as this means 'programming' responses.
So besides that the solution chosen has to be usefull at this moment, it should also be future proof preferably. I'm sure Dan knows that.

**Comment by dasgarner** [comment]
My thoughts were to keep guides, faqs, etc (basically all user facing items) in the [manual](http://xibo.org.uk/manual/en/tour_guides.html). If the manual could be the one stop place to get an answer to a question - then that is great. The key point here is promoting questions to FAQ status by writing a well thought out explaining article and adding it to the Manual. The Manual is now in markdown format and translatable and pull request-able.

Feature Blueprints and Roadmap (things for developers and contributors) I had thought that the Wiki would provide the best home.

Slightly off topic, the Current roadmap:
1.8 - Playlists and ground works for future development (we need to complete some architecture changes so we add things to complete code and not code that is due to change)
1.9 - New Open Source Player
2.0 - Interactive Signage

**Comment by MedusaDelft** [comment]
I'm completely happy/agree with the manual, blueprints and roadmap answer.

Thumbs up for 1.8! Just out of curiosity: are you using an existing framework?

**Comment by dasgarner** [comment]
We don't use a framework at present - they were pretty ropey/new when we first started and as we have incrementally added to our own framework the effort vs reward for adopting a framework has become very low.

The architectural changes I spoke of involve moving from a Layout being stored as the final XLF (the document the players understand) to a proper relational database structure for the layout which can then be compiled into XLF at the point of use. This will make adding new features (such as playlists) far easier.

They also involve an overhaul of the way permissions are stored, so that granting additional objects permissions becomes far simpler (no need to add extra tables, etc).

This is all underway [here](https://github.com/dasgarner/xibo-cms/tree/feature/playlists)

**Comment by andyblackham** [comment]
While I understand the concern about supporting a dev board and a forum, in my experience, most forums are user to user and there is little input from the actual front line development team.
Maybe 1 person / entity to act as liaison between the two?

I think even google forums would surfice so cost isn't an issue.

The forum(s) are usually split into tight subject areas.  Make a dev area one and put a note directing enquiries over here!

andy

**Comment by riondluz** [comment]
I'd love to see an all-linux forum:)

**Comment by andyblackham** [comment]
@riondluz - what other platforms are there? :-)

**Comment by riondluz** [comment]
andyblackham:

Well, not sure about the glib factor ;)  but with windows not in my lexicon I suppose I meant linux-based
platforms (incl droid) repleat with all the nifty utilities to make for a robust client player (clients being a 
sub-forum?) to support all the (py)client goodness. (Please don't go with java).

Expanding on clients suggests going beyond ubuntu (btw, I'm in the anti-systemd
camp) and integrating xibo into other distros. Be a nice way to answer the thread inquiring about
Rpi's (and duinos in general). Suppose it (mostly) boils down to CEF ATM.

I've been out of touch here for a spell and am catching up here on github.
As this domain is no longer the place for conversation (as it were), I'm signing up on the community
and would enjoy sharing more thoughts; as I now have more time to spare for this.

**Comment by riondluz** [comment]
Keeping this thread going if anyone replies; I have community in the next tab and am perusing it now.
I like the code, the package (Discourse), the look-n-feel; though in terms of functionality I do not see 
threading, tags, searchtools.... so the Subject of "do we need..." suggests something more robust
(an add-on or plugin avail to discourse maybe? - haven't looked. Anything that may expand on
the taxinomy's functionality.)

Sticking with what is currently available, I'm inclined to think that each "blog topic" would be a forum 
and as far as a linux forum I can think of many sub-cats related to the issues I (and you) have
probably dealt with.

Examples off the top of my head and from dir/filenames on my dev host:
general # ex: running off USBstick, firewalls, selinux, sys mgmt, ..., platforms, kiosks
server # ex apache/lighthttpd conf, mysql and db mgmt, backups,
client # ex useful-scripts, DisplayManagers, WindowManagers, Screen-Display-Console
           (disper, dual-screens, Xephyr, Xnest, xrandr, xinput, devilspie), ttys-n-vtswitching,
  graphics # ex: useful-scripts (vid cvt, capture/record, ), cards/adapters, 
           switching displays, video tools, AR-vs-Resolution, Contrast Ratio, mouse-touch, vlc, 
           framebuffering, HDTV, component video, cameras and captures, displaylink
  devices # ex: roku, hdmi/dvi, hyperV, openElec, micro/pico-boxen:Asrock/Asus/Acer/Via...,      
          ARM/x86 (mini-itx), UMPC, wall-warts, sheeva-plug
  displays #ex: resolution charts, mounting, video standards, plasma-vs-lcd, HDMI/DVI, viewing/AR,

I'm sure others will/can offer more and a core structure of sub-topics can be agreed upon.
I'm here, and invested in Xibo precisely because of the community and the leadership
focused on engagement and opensource. Maybe forums are a way for the community to
give back and enrich the membership experience. Build/Enable it and they will come is a good
hope.

**Comment by dasgarner** [comment]
I don't want to dampen your excitement at all, but https://community.xibo.org.uk/ is the result of this issue, not an extension of.

So it would be great if you could post your ideas over on there - I don't think you will get much traction for a forum per topic though :smile:
