### ISSUE TITLE
Elements are animated before the window is visible

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3339]
Elements in v4 get animated before onVisible has been called.

**Comment by rubenpingol-xibo** [comment]
I believe that this is working as it is since we don't have `onVisible` with any of the elements. The `onVisible` callback should be the one calling `$(target).xiboLayoutAnimate(properties)` and we are currently doing this just on the **Rich Text** module.

Going forward, does this mean we have to add `onVisible` to the elements?

**Comment by rubenpingol-xibo** [comment]
> We run it by default, so we don't need to add it to all template, I think.

This is what I'm expecting actually. But in case we have `onTemplateVisible` on the element template, we still have to handle it, right? However, does this mean that we have to do `xiboIC.checkVisible()` as well before calling `onTemplateVisible` of the element?

**Comment by maurofmferrao** [comment]
> does this mean that we have to do xiboIC.checkVisible() as well before calling onTemplateVisible of the element?

Yeah, we need to do that and either call the method or add to the queue like we do for other widgets.

**Comment by ifarzana** [comment]
:white_check_mark: tested
