### ISSUE TITLE
Windows client .Net version?

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#334]
I've got .Net v4.0.30319 installed on the Windows XP machine I want to use, but Xibo 1.7.0 setup still complains that it can't be installed on systems with .net lower than 4.0.

It doesn't let me install. Is there any way to override this check? Because .Net is there for 100%.

**Comment by nagyrobi** [comment]
I've worked it around by installing the client to another Win7 machine and copying the files over manually from C:\Program Files, and it works well using Chromium Embedded Framework. Thank God there's an option to the non-existent Internet Explorer.

So it seems there's a little issue with the installer .net version check.

**Comment by dasgarner** [comment]
Hmm... that is odd. 

We use a 3rd party MSI builder which is responsible for doing the check (and hasn't changed for some time).

Copying the files over should be sufficient - the only thing you will be missing is the entry in control panel.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
