### ISSUE TITLE
Dataset Issue

### ISSUE THREAD

**Issue by coopernicholas** [xibosignage/xibo#3403]
The local datasets will not download to the players. I have tried a Windows and Linux players. The error on the CMS is "getData: Failed to get data cache for widgetId 156, e = Cache not ready" The player says no data. Any help would be greatly appreciated.

**Comment by dasgarner** [comment]
Hi and thank you for getting in touch. 

It looks like this might be a support request.

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
