### ISSUE TITLE
Screensaver config multiple users (network use)

### ISSUE THREAD

**Issue by Stodge1000** [xibosignage/xibo#349]
How can we pre config screen saver for all users of the machine? it seems all users have to configure when moving to a new machine.

can we default config this somewhere?

**Comment by dasgarner** [comment]
The config is stored in the user profile in an `xml` file. If that xml file doesn't exist a copy of the "default" XML file is taken from the installation folder.

You could update the default XML file with your required values (CMS url, key, etc)

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
