### ISSUE TITLE
Weather Widget: not displaying images

### ISSUE THREAD

**Issue by JeroenTuinstra** [xibosignage/xibo#3513]
Windows player 4 R403.1 
Xibo Server 4.1.0

The image element from the Weather widget does not work. In layout it shows the picture and you can edit it. However in the player the image is completely ignored. Using the static template "Scale - Weather background only" the picture corresponding with the weather condition is displayed.
So it is only the image element that refuses to load or be displayed in the player. Also when you use/replace image with your own image, the image is not displayed.

**Comment by dasgarner** [comment]
Hi and thank you for getting in touch. 

Sorry but we're not completely sure what you mean from your description.

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
