### ISSUE TITLE
JSON dataset cannot update other than Fetch Remote Datasets

### ISSUE THREAD

**Issue by c769214** [xibosignage/xibo#3536]
Hi, 

Using 4.1.1 CMS on docker , setup looks ok.

On Administration → Tasks , I found “Fetch Remote DataSets” is runnnig on every 30 minutes and all datasets can update correctly in each 30min of the hour.

But when I created a new layout and using datasets and I found all json related datasets cannot updated even I preset any time and no updates (only the value in “Fetch Remote Datasets” working

Inside the layout all others can be updated (eg: I asked to update a picture in 3 mins and it will reload a new pic)

Kindly please advise which part I need setup/update?

**Comment by c769214** [comment]
JSON link, (data updated in every 10 sec)
[https://rt.data.gov.hk/v1/transport/mtr/getSchedule.php?line=ISL&sta=CEN](url)

**Comment by dasgarner** [comment]
Hi and thank you for getting in touch.  It looks like this might be a support request.

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
