### ISSUE TITLE
Unable to add new playlists after removing dynamic playlist in layout editor

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3538]
When working in the layout editor, if two dynamic playlists are added to a single playlist, removing one of them causes issues. Specifically, removing one dynamic playlist prevents the addition of any new playlists.

Steps to Reproduce:

1. In the layout editor, add an empty playlist.
2. Add another empty playlist and add two dynamic sub playlists.
4. Remove one of the dynamic playlists.
5. Click on the back button to move away from the playlist window
6. Observed layout editor

Observed Behavior:
The Playlist in the viewer then shows a dynamic playlist icon and not the playlist with dynamic subplaylist

**Comment by maurofmferrao** [comment]
I believe that the behaviour is like that by design. If it’s a Playlist with a single Sub-Playlist, it will behave like if the external playlist is added to the Layout.

- Add an empty playlist
- Edit playlist and add a sub-playlist with a single playlist
- Go back to Editor
- Click edit again
- The playlist now being edited is the playlist that was selected in the sub-playlist drop down

So I think the same is happening with the Dynamic, since it’s the only added to the external playlist, it’s transforms into the dynamic in the layout level.

**Comment by maurofmferrao** [comment]
The best way to solve this issue is by implementing a dedicated Playlist Mixer widget (https://github.com/xibosignage/xibo/issues/3545) to simplify the management of Playlists inside Playlists.
