### ISSUE TITLE
Android Player issue

### ISSUE THREAD

**Issue by ekinkaradagg** [xibosignage/xibo#3563]
Hello, I want to ask a simple question. I want to create my own Android player. I’m downloading the required files with the necessary files. The getResource API doesn’t return a valid HTML response if there is only a video in the layout. Likewise, the returned HTML response doesn’t include elements like video or playlist. Where am I going wrong? How should my setup be?

**Comment by dasgarner** [comment]
Hi and thank you for getting in touch. 

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
