### ISSUE TITLE
Image/Region Getting Cut Off

### ISSUE THREAD

**Issue by bdk6000** [xibosignage/xibo#357]
When I start up my Xibo Player and let it run, everything looks properly at first. I'll let it run for a couple hours, and when I come back to check on it, the bottom part of one of my regions is cut off slightly. It is a region with a png image inside it. It always looks fine at first, but after awhile it ends up getting cut off on the bottom. Not sure what the cause is.

I'm on Windows 7 running the latest version.

**Comment by bdk6000** [comment]
![before-after](https://cloud.githubusercontent.com/assets/11232430/6416420/11615236-be74-11e4-8ca4-872d8a7ecea4.jpg)

**Comment by dasgarner** [comment]
I'm impressed you managed to get the ticker at more or less the same point when you took the screenshot :smile: 

As for the problem - that is an odd one. It looks like something has been overlaid on the top. Would you be able to provide a layout export? Or perhaps a CMS url we can connect to and try?

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
