### ISSUE TITLE
Add Google Calendar

### ISSUE THREAD

**Issue by pmeagher** [xibosignage/xibo#359]
I am having a hard time having google calendars display on my layout. I display a webpage that has the calendars, but after 1 or 2 minutes it just displays a white box. I have tried a ticker but could not find one to scroll through them how the user wanted. Does anyone have any good ways to make this possible?

**Comment by nagyrobi** [comment]
http://fullcalendar.io/

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
