### ISSUE TITLE
How can I participate in bug fixing?

### ISSUE THREAD

**Issue by andyblackham** [xibosignage/xibo#360]
I've rased a couple of bugs around missing graphics and I can make the missing images for the project.

Do I need the bug assigning to me or shall I just make some images in my documentation branch and let you know?

What's the best route?

andy

**Comment by dasgarner** [comment]
Hi Andy,

Its best to get the bug assigned to you before you make the fixes - so that you don't end up fixing things twice.

I've resolved a lot of those missing image bugs already, so there is a chance the bug is already resolved.

If an issue hasn't been tagged as a bug then there is a good chance it is a duplicate and there is another tagged issue.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
