### ISSUE TITLE
[CMS 1.6] - media upload canceled when leaving page

### ISSUE THREAD

**Issue by martialgallorini** [xibosignage/xibo#366]
Hello,

I am using Xibo CMS 1.6 with python client. I noticed that when i upload a media from the CMS i have to stay on the upload page until it is finished otherwise the transfer is canceled. 

I sometimes need to send big video files so i need to stay on the upload page quite some times. It should be great to make the transfer in the background

thanks a lot

**Comment by dasgarner** [comment]
Websites don't really work in that way unfortunately - when you navigate away from the page all actions that are being taken are aborted.

I agree it would be a nice feature, but I am not sure how it would be possible (perhaps we could write some sort of browser extension for it).

If anyone has any ideas - great.

Thanks,
Dan

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
