### ISSUE TITLE
Can't find usage of a string

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [xibosignage/xibo#38]
Hi,

I'm working on some translations on your launchpad site.
To be sure I get the right words in my language, I'm looking the words up where they appear in Xibo.

But I can't find "Lock Module Config" (Located in server/locale/dbtranslate.php:98 ). I've looked up all settings pages. I just can't find it.

**Comment by dasgarner** [comment]
That is actually a hidden setting for service providers that is used to lock access to the Module Configuration page - so that users cannot edit the module settings.

A typical example would be if a service provider has chosen not to support a particular media module (like PowerPoint), they disable the module, but don't want the end user to be able to go in and enable it again.

Hope that makes sense?

**Comment by Speedy-Gonzalez** [comment]
Now I get it. Thanks.
