### ISSUE TITLE
[CMS 1.6] - Media upload : internal server error

### ISSUE THREAD

**Issue by martialgallorini** [xibosignage/xibo#383]
Hello,

When uploading a video (MP4) in xibo CMS i keep getting "Error : internal server error" after about 10 minutes.

I specify i am trying to upload a large file : 11 GB

I think i have set my server accordingly : post max size, script max execution time, session max time etc... 

could it be a Xibo issue ? or a server issue ?

thank you

**Comment by alexharrington** [comment]
11GB is very large. I'm not sure most webservers will support uploading a file of that size (that's the underlying webserver not Xibo itself). The problem is that the file when uploaded via HTTP goes up as a POST request and so will have to be parsed in RAM by the webserver.

You will probably have to upload a file that large via the API where chunked uploads are supported.
