### ISSUE TITLE
Xibo Admin Login returns with session expired

### ISSUE THREAD

**Issue by Nefraim** [xibosignage/xibo#394]
Hello,
I have succesfully installed the Xibo CMS on my hosting.
But after the installation, while im trying to logging in;  im getting :
''Sorry the form has expired. Please refresh.''
I've tried everything on the past topics in the internet about Xibo CMS.
What should i do? It is a long last issue i see in the topics. Are there any solutions found for that?
I'll provide every required data as i can.
Thank you.

**Comment by dasgarner** [comment]
It sounds to me like your session is invalid - do you have cookies enabled on your browser?

Xibo uses PHP sessions with an added UserAgent check (your browser UserAgent can't change between requests).

**Comment by nagyrobi** [comment]
I had the same issues when I had other web services running on the same IP address with Xibo CMS. The other web service also threw me out with similar errors. Seemed like both were trying to use the same cookie or session or something.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
