### ISSUE TITLE
Help with embedded content (java)

### ISSUE THREAD

**Issue by solane** [xibosignage/xibo#403]
I am having trouble getting embedded content to run on xibo clients. I have used the widget from twitter which allows you to view tweets on your client Tv's (BBC News in my case) so that I can display news items on the noticeboards around school however... The twitter feed works when I'm previewing the layout from my management console but won't work on clients. The layout designer is complaining that 'There are items on this layout that cannot be accessed by the client' but I have no idea where I'm going wrong. It must be to do with the way I've set up the JavaScript but I have no technical knowledge in this area.

Thanks
Sam

JavaScript:
![twitter feed](https://cloud.githubusercontent.com/assets/10942349/6527019/2984a9b2-c40f-11e4-9db4-35686821adb8.JPG)

**Comment by mattgrimley** [comment]
Hi @solane
I'm not in front of my install until Monday, but we had issues with our embedded Twitter stream because of a change Twitter made late last year. It might be the same issue!

Effectively, the issue was two-fold: Twitter broke compatibility with old versions of Internet explorer and Microsoft unilaterally decides to run their cutting edge modern browser in 10 year old "compatibility mode" for ie7 when accessing any website it considers to be in your on intranet (i.e. your XIBO server).

This link provides the background for the fix, https://answers.launchpad.net/xibo/+faq/2246

However, for me, i had to use 9999 rather than 9000 as the registry entry (this link explains the difference: http://superuser.com/questions/321403/how-to-change-browser-mode-in-ie9-permanently).

**Comment by solane** [comment]
@mattgrimley 

Life-saver! Worked perfectly :) 

All hail Microsoft....

Thanks
Sam
