### ISSUE TITLE
Problem in Scheduling

### ISSUE THREAD

**Issue by JanTee** [xibosignage/xibo#407]
I get this error when i try to schedule in xibo 1.7.1
It also put 3 - 5 schedules up instead of the one i want

1896279 	2015-03-09 13:29:23 	CMS 			<errormsg>Undefined variable: type</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>/var/www/xibo/lib/service/xmdssoap4.class.php</scriptname>
<scriptlinenum>932</scriptlinenum>
1896277 	2015-03-09 13:29:23 	CMS 			<errormsg>Undefined variable:

**Comment by dasgarner** [comment]
That error isn't related to scheduling, it is a non-critical problem with the register call from Displays. Can you report in the community site and state your exact problem?


----
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
