### ISSUE TITLE
Recurring is not working properly

### ISSUE THREAD

**Issue by newburns** [xibosignage/xibo#409]
When I create a new layout and it has two regions. One region is 2 minutes, the other is a video that is 5 minute.
I set the 1st region to recur on the region option. There are several videos within the region timeline.
However, when displayed on the client, the video timeline does not restart as the other region continues to finish.

**Comment by dasgarner** [comment]
You are right, the "loop" box isn't working correctly on Windows Players yet. I have added a note to that form stating that in 1.7.2.


------
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
