### ISSUE TITLE
Changing Passwords

### ISSUE THREAD

**Issue by pmeagher** [xibosignage/xibo#410]
I am having an issue with my users not being able to change their passwords. They go to their username in the top right and select change password; however they do not have permission to do so. I didn't see anything in the permissions structure. Has anyone else seen this issue?

**Comment by xibo-de** [comment]
It just did not work but when I deleted the session table, then it works.

coincidence fortune ?

**Comment by dasgarner** [comment]
To change their password they need page permissions for the `user` page group.


-------
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
