### ISSUE TITLE
Webpage not showing 100%

### ISSUE THREAD

**Issue by serifcakir** [xibosignage/xibo#414]
Hi 

I have the problem that the webpage only showing a little bit in left corner.

What is the problem?

Im using windows client

**Comment by mbreckers** [comment]
I had a similar issue temporarily, I had to wait until the client downloaded xibo_layout_scaler.js

**Comment by dasgarner** [comment]
If it doesn't download that file (it should really be downloaded first, but I guess not!) then please try and use the Verify All option on the Modules page in the CMS.

-------
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
