### ISSUE TITLE
xmds.php high usage

### ISSUE THREAD

**Issue by mbreckers** [xibosignage/xibo#415]
Setup:

Xibo Server 1.7.1 running on my domain hosted by a cloud-based hosting company.
Xibo Client 1.7.1 running on a Windows 7 x86

I have been having several issues lately, mainly one file that wont download to the client, it's a random string followed by .htm extension (example: "resource: 245fe5cf7e0c39bfab9331e05cf47c62.htm")

It just always sits at 0%.

The other day I get an email from my hosting company:

"We have received an urgent / emergency alert from our cloud platform that the below process bound to [Domain Removed] has used over 12,000 IOPS per second / 12GB RAM and 2,129% CPU usage over the past few hrs. To protect our other customers we have had to suspend this domain however can we have an urgent call to discuss the site and what we can do this side to better manage it.

Full trace below:

555092W 19    1.37  [DOMAIN REMOVED]          [IP REMOVED] POST /xmds.php?v=4 HTTP/1.1"

Plus a sample of their log file:  http://pastebin.com/PxMGpNu8   (way too big to post directly)

Any ideas on what could be causing this and more importantly, how to fix.

**Comment by dasgarner** [comment]
XMDS is the service every player will use to get its content from the CMS - each player will make a bunch of connections to that service in order to operate correctly.

GetResource is the end point which would generate that "resource: blahblah.htm" file - if it is 0 it means it cannot be downloaded for whatever reason. Perhaps you have a RSS feed which can't be downloaded or similar. You would need to check the error log on the CMS to find out exactly why.


Looking at the log - it doesn't look particularly alarming - the requests aren't coming in that fast. How many displays do you have connected?

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
