### ISSUE TITLE
Requires PHP FileInfo support to function. If you are on Windows you need to enable the php_fileinfo.dll in your php.ini file.

### ISSUE THREAD

**Issue by fieldmedia** [xibosignage/xibo#421]
Hi All...

So not had this issue before.  I've installed older versions of Xibo on other machines with XP.  Installing on Windows XP machine.  Installation comes up with a nice cross on the line - Requires PHP FileInfo support to function. If you are on Windows you need to enable the php_fileinfo.dll in your php.ini file.

I've looked across other forums...  not solved it so far.  Anyone else had this issue and how did you fix?

Thanks

Kevin

Not a novice but hey go easy with the code.. learning every day. Advice always welcome.

**Comment by dasgarner** [comment]
We are moving discussion and support over to community.xibo.org.uk, so we would appreciate you asking on there in future.

Regarding your issue - "file info" support has been added fairly recently, so that would explain why you haven't had to enable it before.

[Installing extensions on windows](http://php.net/manual/en/install.windows.extensions.php) is easy and the php_fileinfo.dll extension should be bundled with the installation (if it isn't then it is likely the version of PHP you are installing is too low).

There are plenty of articles giving detailed steps for this if you search for `php windows php_fileinfo.dll`, however the basic process is:

 1. Find the PHP installation, look in `ext` and make sure the file is there
 2. In the PHP installation, look for `php.ini` open it
 3. Search for php_fileinfo.dll and you may find a commented out section, if you do then uncomment it, if you don't then add a line for it
 4. Restart your web server

**Comment by alexharrington** [comment]
For future reference this is now included in the FAQ:
https://community.xibo.org.uk/t/how-do-i-enable-fileinfo-in-php-on-windows/78
