### ISSUE TITLE
RSS no updating on python client (1.6)

### ISSUE THREAD

**Issue by misioooo** [xibosignage/xibo#422]
Hello. I am using Xibo server 1.6 and mix of windows and python clients.
On windows all works fine. On linux RSS is not updating (xibo displays cached data?)... Any ideas how to solve this?

**Comment by dasgarner** [comment]
The Ubuntu Player has been discontinued (it has never been released as a stable release). See: http://xibo.org.uk/2014/12/15/xibo-for-ubuntu-alpha-discontinuation-notice/

You may be able to get some support for it on the below link.

-----
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
