### ISSUE TITLE
Transition appears in the timeline when disabled

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#424]
Hello Dan, it's nothing important, but planning on having more usable space in the timeline, I think we could hide the display of transition if you have nothing set for input or output item. Even with the disabled transitions is still shown on the timeline.
![image](https://cloud.githubusercontent.com/assets/325662/6609788/05b2a762-c835-11e4-843d-081f88970f43.png)

![image](https://cloud.githubusercontent.com/assets/325662/6609772/d3e15bac-c834-11e4-9c4f-d35c533d2fab.png)

Suggestion
![image](https://cloud.githubusercontent.com/assets/325662/6610178/53d4bd72-c83a-11e4-9390-9a908e05c5b5.png)

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
