### ISSUE TITLE
Adding Volume Control for displays

### ISSUE THREAD

**Issue by Pavi-thra** [xibosignage/xibo#428]
How to add a new functionality in xibo server 1.6 for controlling the volume of the registered displays ?

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
