### ISSUE TITLE
Forecast IO behind PROXY server 

### ISSUE THREAD

**Issue by jopper1988** [xibosignage/xibo#430]
I know i have made this topic before but the proxy isn't blocking the connection. But with the change in

https://github.com/xibosignage/xibo/issues/298

Doesn't make different. So what is going on? And what can i do to make it work. Already make a report fault but the only thing i can find is that the twitter api isn't be found.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
