### ISSUE TITLE
Empty Log

### ISSUE THREAD

**Issue by cgslaughter** [xibosignage/xibo#452]
I recently re-did my entire xibo install and all clients. I am running version CMS 1.7.2, and Android Clients 1.7r53.  I have turned on audit on the CMS and some of the Clients. I get nothing in the log. (Log also was not working before hand, after upgrading from CMS 1.6.3)

I was told that the problem is most likely caused by table corruption, however, I have checked the mysql tables and they all come back fine. All other PHP and MySQL based programs seem to have no problems.

Server is Windows Server 2012 64 Bit, MySql 5.5, PHP 5.5.11, IIS 8.

<strike>The only thing I can think of is that I do have some layouts that have more than 40+ entries, all of which are JPG and MP4 files. Wondering if it could possibly be related to: https://github.com/xibosignage/xibo/issues/340</strike>

<strike>I am wondering this because on some of the layouts they play part way through the layout and then go blank.</strike> It was a corrupted jpg that caused this.

Possible related: https://github.com/owncloud/core/issues/992 , I know it is different software altogether, but Windows Server 2012 and errors I get in err_log.xml are a match.

My error in err_log.xml:

IN
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'mediaID' at row 1

**Comment by cgslaughter** [comment]
Problem is that the mediaID Type is incorrect. It was set to INT. As soon as I changed it to tinyblob it started populating. Problem is in the how the database is created during install.

**Comment by dasgarner** [comment]
There shouldn't be **any** columns that are a "tinyblob" - we do not use that datatype for anything, least of all an ID column (which should be an INT).

It might be something related to the version of MySQL you are using that is not liking the way those variables are substituted.

Can you try and change this [debug.class.php](https://github.com/xibosignage/xibo-cms/blob/develop/lib/app/debug.class.php#L274)

to:

``` php
                'displayid' => Kit::ValidateParam($displayId, _INT),
                'scheduleid' => Kit::ValidateParam($scheduleId, _INT),
                'layoutid' => Kit::ValidateParam($layoutId, _INT),
                'mediaid' => Kit::ValidateParam($mediaId, _INT)
```

Reverting your blob change in the process.


FYI - these sorts of things should be posted on the community forum first so that we can discuss before verifying it as a bug. Cheers!

**Comment by cgslaughter** [comment]
Dan,

Thank you for your response.

I apologize for not posting to the correct location.

I have made the changes to the debug.class.php  file as requested and reverted the blob change. The log is working as expected.

Thank you.

Colin Slaughter
