### ISSUE TITLE
DataSetView doesn't take up full height when Rows Per Page is selected

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#550]
The cycle plugin seems to prevent the expansion to region width/height.

More details here: https://community.xibo.org.uk/t/topic-extension-cms-1-7-4-dataset-view-css-bug/2851

**Comment by haqr1ab** [comment]
I too have been having this problem. Currently using 1.7.6 on Windows 7, 32 and 64 bit. One thing I found that might help narrow down the issue is if I change the schemaVersion value from 2 to 1 in the XML then it will display properly, complete with cycling through the pages.

Just thought it might help in locating the problem.

**Comment by dasgarner** [comment]
I am pretty sure this has all been tidied up long ago, so I am closing this out. If it isn't resolved, please post on our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can. Thanks!
