### ISSUE TITLE
LayoutRegionMediaEdit using RestXML API results in a empty $user->db

### ISSUE THREAD

**Issue by fenrig** [xibosignage/xibo#553]
When I issue LayoutRegionMediaEdit with the API (in python) I get an empty database object in my module which is because in "rest.class.php" (in lib/service/) on line 968 in the "public function LayoutRegionMediaEdit()", tries to create a module using: 
"$module = ModuleFactory::load($type, $layoutId, $regionId, $mediaId);"

This results in ModuleFactory.class.php (in lib/modules) creating a new Database object and a new User, this is wrong because the following code in the corresponding module tries to use that user to connect to the database (which is not connected or anything) to fail on the sql query.

But I've found the solution:
-----------------------------------------
That's why "rest.class.php" should hand it's user ($this->user) to the modulefactory like this:
$module = ModuleFactory::load($type, $layoutId, $regionId, $mediaId, NULL, NULL, $this->user);
in the "public function LayoutRegionMediaEdit()", around line 968

**Comment by fenrig** [comment]
Oh yeah forgot to add that this applies to the xibo-cms, how come the API is so broken?

**Comment by fenrig** [comment]
I forked the CMS and pushed the change to it, if you guys want I can issue a pull request

**Comment by dasgarner** [comment]
Hi @fenrig,

Thanks for your contribution - the API is broken in places (you could say many places) because it is not actually released yet. It is in beta and has the features implemented on a request by request basis.

We are completely reworking the API for 1.8 (this release will be stable API release). You may want to look at this branch: https://github.com/xibosignage/xibo-cms/tree/feature/playlists

This will be merged into `develop` soon to facilitate a 1.8.0-alpha release at the end of August.

**Comment by fenrig** [comment]
Oh yeah okay, I'll take a look at it when there is a alpha! Thanks
