### ISSUE TITLE
using Xibo with distant server

### ISSUE THREAD

**Issue by kool1999** [xibosignage/xibo#557]
HI everybody,

I installed xibo in local machine (player and server) everything is ok; now i need to install player and server in different location. I install server in one location and player in another with this in player option: http://x.x.x.x/xibo   (x.x.x.x: is the address domain of my server, i put the same key of my server) but i get always ( unable to connect to server) . How can i fixed that §§§§.
I use the last version of xibo with win7

I have the xibo installed in different locations, and i don't need for any change of the layout to travel to do that.

Many thanks

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
