### ISSUE TITLE
display always being unkwon status

### ISSUE THREAD

**Issue by nelsonjmmarques** [xibosignage/xibo#559]
uhm hi and im having a problem, working on a company (internee) and im facing with the problema that the display suddently is now being(even when working on the own original source) unknow. and when i export a layout i get error 11, is there anithing i can do to stop this error or fix the display?
![capturar](https://cloud.githubusercontent.com/assets/13553802/8955400/358ec106-35e4-11e5-9d32-3add89b4bd5b.PNG)

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
