### ISSUE TITLE
User password expiration time

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#587]
It could be a good idea to add an option to set user password expiration time.
For example: Passwords must be changed every 120 days.

**Comment by ngi32487** [comment]
This issue is more than 4 years old and maybe it's time to close it, therefore I'll give it a short update:

Password expiration was somehow necessary in the past and it is still practice today as it's fixed in administrators' minds, but should not be enforced anymore. In practice it decreases security as users then choose weak passwords so that they are easier to remember (most users just increase the last digit of the password by 1 and everybody, especially hackers, know that...).
Refer to: https://www.sans.org/security-awareness-training/blog/time-password-expiration-die

Changing the password is only necessary, when the database was hacked, but in such a case changing the password alone without rethinking server security won't prevent hackers from hacking the database again...

To keep it short: if access to the server is sufficiently secure (absolute security is not possible) and passwords are stored using a strong hash algorithm, then it won't be necessary (but rather counterproductive) to change passwords.

**Comment by dasgarner** [comment]
Thank you for the update - I tend to agree with you, particularly as we have the option to use Two Factor Auth or SAML.

I will close out this issue as not required.
