### ISSUE TITLE
Xibo Display IP Address Wrong when behind a proxy

### ISSUE THREAD

**Issue by misilot** [xibosignage/xibo#606]
Hello,

It appears the IP Address for displays ends up being wrong when the Xibo Server is behind a proxy such as HAProxy

**Comment by dasgarner** [comment]
You are quite right (any sort of proxy in fact) - however there is not much we can really do about it. The proxy server should pass on the correct IP address, but it it doesn't then it doesn't.

We could consider a change so that the Player sends its IP address - but then there is a NAT issue.

I've logged as a backlog bug to see if we can come up with a cunning plan.

**Comment by misilot** [comment]
Most proxies use the  X-Forwarded-For header would that work as something
to check?

**Comment by dasgarner** [comment]
I do apologise - I only checked the latest development code, which uses `'X_FORWARDED_FOR', 'HTTP_X_FORWARDED_FOR', 'CLIENT_IP', 'REMOTE_ADDR'` in descending order to get the IP.

I've made a small change to 1.7.5 which will do the same there too
