### ISSUE TITLE
Overlaying layers in Windows client

### ISSUE THREAD

**Issue by jwktje** [xibosignage/xibo#620]
Overlaying sections in the Windows player aren't respected.
I remember seeing somewhere on the forums a while back that this was being recognised by you guys and just not supported yet.
Wanted to know if this is on the roadmap and if there is a way to support/help toward this being implemented.

**Comment by dasgarner** [comment]
We're only using GitHub issues to track verified bugs, so in future please can you comment on the forum? You can use your GitHub credentials.

----

This is not going to be implemented in the current windows player because it requires a complete rewrite - therefore it will happen in 1.9 when we release a new player for Windows/Linux.
