### ISSUE TITLE
1.64 -> 1.7 upgrade SQL Error 80 - [SQLSTATE[42S21]

### ISSUE THREAD

**Issue by pb7892** [xibosignage/xibo#65]
Hello all.

"An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 80. Error Message = [SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'render_as']"

That is what it returns during the upgrade.
Do you have any idea ?

Tx all.

**Comment by dasgarner** [comment]
This might be due to a failed upgrade previously - we found a small problem if your 1.6 CMS used custom resolutions.

The best thing to do is to revert to 1.6, delete any custom resolutions and then try again.

There is a patch for the customer resolution problem here: https://github.com/dasgarner/xibo-cms/blob/develop/install/database/80.sql - just replace that file.

**Comment by pb7892** [comment]
Thanks for answering. I tried an upgrade before seeing that the most important issue for me won't work which is the Linux client. I stop investingations now.
