### ISSUE TITLE
Python Client + javascript webpage

### ISSUE THREAD

**Issue by martialgallorini** [xibosignage/xibo#66]
Hello,

I am using Xibo CMS 1.6 with python client on ubuntu 12.04.

I have a web page to display. This page displays animated gifs. Those images are retrieved from an FTP server and refreshed every 10 seconds. According to the developer, refresh is done with some javascript code.

Xibo displays this page ok except it doesn't refresh the images.

Everything runs smooth in Chromium

any idea ?

thanks a lot

**Comment by nagyrobi** [comment]
Is the page refreshing itself in the browser?

**Comment by martialgallorini** [comment]
Yes the page acts as it should in Chromium browser

**Comment by nagyrobi** [comment]
Maybe you should set the Duration of the webpage to 10 seconds in Xibo layout design.

**Comment by martialgallorini** [comment]
Thanks for the suggestion. I will try when i can.
But i doubt it is the solution. I mean, maybe the page will refresh and show new pics. But Javascript here generates transitions between images like wipes. This doesn't work.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!

There is a topic where a user has offered their services [here](https://community.xibo.org.uk/t/unsupported-raspberry-python-xibo-client-we-may-help-you/59).
