### ISSUE TITLE
1.7.6 bandwidth log has duplicate entries for some months.

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#762]
![image](https://cloud.githubusercontent.com/assets/10450518/14279629/2758a5f4-fb26-11e5-94e1-f27213314a40.png)

It seems something adds an extra record to the db for a stats log action which is 1 hour different from the rest of the logs. 

For example:

> select * from bandwidth where month > 1459546000;
> +-----------+------+------------+----------+
> | DisplayID | Type | Month | Size |
> +-----------+------+------------+----------+
> |         6 |    1 | 1459548000 |  1680084 |
> |         6 |    2 | 1459548000 | 29937766 |
> |         6 |    3 | 1459548000 |  1067850 |
> |         6 |    4 | 1459548000 | 14878165 |
> |         6 |    5 | 1459548000 |  3341902 |
> |         6 |    6 | 1459548000 | 12405552 |
> |         6 |    7 | 1459548000 |    60540 |
> |         6 |    8 | 1459548000 |  2893331 |           <<<<< 1st April 10pm
> |         6 |    8 | 1459551600 |     1499 |               <<<<< 1st April 11pm
> |         6 |    9 | 1459548000 |   603333 |

**Comment by dasgarner** [comment]
I think the correct way to handle this would be to change the `bandwidth` table so that we have 3 columns:

 - month
 - year
 - date

We update the old records such that they:

```
UPDATE `bandwidth` SET `month` = MONTH(FROM_UNIXTIME(month)), `year` = YEAR(FROM_UNIXTIME(month)), `date` = UNIX_TIMESTAMP(STR_TO_DATE(CONCAT(`year`, '-', `month`, '-01 01:00:00'), '%Y-%m-%D %h:%i:%s'))
```

We then add `year` to the primary key on the table.

We then update XMDS CheckBandwidth and LogBandwidth to use `date("M")` and `date("Y")` instead of the current mishmash. 

The status dashboard and statistics page would group by month and year.

----

Seems like a massive faf - so need to think about it.

**Comment by dasgarner** [comment]
Perhaps doing this would solve the issue going forwards:

```
strtotime('first day of this month')
```

**Comment by dasgarner** [comment]
A solution already existed in 1.8 - grouping by the MONTH sql function on the status dashboard query will correctly aggregate duplicates.
