### ISSUE TITLE
Error when adding content to a region's timeline

### ISSUE THREAD

**Issue by brodkin** [xibosignage/xibo#823]
Hi guys,

Ran into another bug in the current Docker image... I created a layout and assigned an item to the timeline. I saved and it showed up on my display as expected. Any subsequent timelines to which I add media result in the following error being displayed:
```
Fatal error: Call to a member function create() on a non-object in /var/www/cms/lib/Controller/Module.php on line 420
```

**Comment by alexharrington** [comment]
I just ran up the 1.8.0-beta container, created a new layout, added an image to the region. Then created another layout, and added a different image to the region on that one without seeing any errors.

Perhaps it's worth checking that you're on the beta container and not the old alpha 3 one? And perhaps worth checking with a fresh database too - since I don't know what issues you may have hit with the alpha release.

In general, we ask that people discuss any issues they have over on the Community site, before opening a bug report here. Github Issues doesn't work for us as a platform to provide support, so we don't use it for that.

**Comment by brodkin** [comment]
It was actually a clean install with a clean database using the current image. I'll see if I can find more details that will help you reproduce it.

**Comment by dasgarner** [comment]
I can confirm this as a bug - the permission factory is not passed in correctly by DI

**Comment by dasgarner** [comment]
@PeterMis - can we have a test for this please?

**Comment by brodkin** [comment]
I'm glad you guys were able to find this. I spent a couple hours trying to reproduce it yesterday but couldn't. I thought I was losing my mind.

**Comment by dasgarner** [comment]
It had me confused for quite some time too!
