### ISSUE TITLE
Improve PDF module with duration per page

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#944]
Perhaps we could add support for duration per page for this module?

**Comment by dasgarner** [comment]
This is not easy, because we don't know the number of pages until the document has loaded and therefore cannot use the controlMeta used by Tickers, etc to override the duration specified in the Layout.

To get this to work we would need a JavaScript method callback (a binding between the web view and the application logic) to alter the duration of a media item after it has started.

**Comment by dasgarner** [comment]
We can use a web hook for this - if we publish a special endpoint in the Player to "/setWidgetDuration" we can make the PDF module call it, providing its widgetId and the new duration as a POST request.

We'd need some JavaScript shipped and included on all modules which declared some functions to use for this purpose.
