### ISSUE TITLE
Shipped "Users" group cannot add widgets to a layout

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#958]
The permissions that ship for "Users" don't allow users to create widgets on layouts.

You need the "User" role in the permission to get that working, but that then gives them permissions to create users.

**Comment by dasgarner** [comment]
Seems like a 3 fold problem:

 - Having the user permission or not shouldn't effect adding widgets the layouts (there is a JS error)
 - The user permission should be assigned by default so that the user can change their password, etc (it is already, but only since #883 
 - Having the user permission should not expose the user administration menu, unless the user can also administer users (group admin or super admin)
