### ISSUE TITLE
Option to delete all unused files

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#98]
With use, the user will inserting videos, photos and with time to removing timeline. These files on it are just disconnected the timeline, and are in the library.

I would question the possibility of giving the user the option of deleting all unused files, that is, everything that is not associated with any particular region or background.

Is it possible?

Dan, if you can not enable the short term, could generate a SQL script and CMD to perform this function by user ID. I had trouble to get the query to generate library items that are background.

**Comment by dasgarner** [comment]
``` sql
SELECT * 
   FROM media 
  WHERE type = 'video' 
    AND mediaid NOT IN (SELECT DISTINCT mediaid FROM lklayoutmedia) 
    AND mediaid NOT IN (SELECT DISTINCT mediaid FROM lkmediadisplaygroup);
```

Should get you all video files that are not associated to a layout.

A user function that deletes all unused media sounds like a sensible idea - although it might be a long running function and therefore might be better placed in the maintenance queue.

**Comment by laercionit** [comment]
This generates a list of content that is not in any particular region.
But we can have images that are background.

Furthermore we have the files on the disk ...

Ideal would be a script to inform the user ID and generate delete the basis
of what can be erased and another script that generates CMD command to
delete the disk ..

Can you help me? I'm afraid to delete something wrong .rsr..rs.

*Laercio Junior*
Cel./Pessoal: (21) 99162-7440
Email Pessoal: laercionit@gmail.com
MSN: laercionit@hotmail.com
Skype: laercionit



2015-01-29 15:59 GMT-02:00 Dan Garner <notifications@github.com>:

**Comment by dasgarner** [comment]
Background images will be in lklayoutmedia with a regionID of "background" - 1.7 layouts only! In 1.6 it is very difficult to get the background path as it is within the Layout XML only.

You are correct that will generate all media, but you can restrict it to only media that user owns by adding `AND media.userId = :userId`


Obviously the above is a temporary thing and will allow you to identify media that is no-longer in use and delete it from the UI.

The final solution would be a good deal more complicated, because there are lots of other things to consider for the delete - file revisions for example. I think this would be better left for 1.8 due to the restructuring of the database that will occur to support playlists.

**Comment by laercionit** [comment]
Dan, this item could be scheduled for release 1.7.2 with investment in development? If so, could you tell me the cost of evaluation?
