### ISSUE TITLE
Weather module language issues

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#998]
Some languages seems to not attempt to translate days of the week and month of the year in any template that should show it, those languages are - Norwegian, Tetum, Belarusian, Bosnian, Igpay Atinlay and Traditional Chinese.

That could very well be something with dakrsky api that's causing this problem.

Special characters in day of the week are also not always displayed correctly, definitely ą,ł are not displayed correctly, instead is shows 
![image](https://cloud.githubusercontent.com/assets/12148978/21685172/6d3b00a2-d358-11e6-8111-a85ef1d459c1.png)
Although Turkish or simplified Chinese characters are displayed correctly.

**Comment by dasgarner** [comment]
The languages that are supported by the date/time functionality are listed here: https://github.com/jenssegers/date/tree/master/src/Lang - these are not necessarily the same as the ones supported by the DarkSky API. If this issue was generated by a particular support request, we could ask if that person is willing to submit a translation file to the upstream library project.

Regarding the odd characters on some dates - this is due to the use of the short format `D` in most templates. The library we use takes the first 3 characters of the translated date using `mb_substr` - unfortunately this only works reliably if the `mb_internal_encoding` is set to UTF-8. I have made a change to support that.

It would be better to avoid using sub-string altogether as this doesn't make sense in all languages, there is an upstream issue for that here: https://github.com/jenssegers/date/issues/226
